# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.label_value import LabelValue
from hindsight_client_api.models.map_field_output import MapFieldOutput
from typing import Optional, Set
from typing_extensions import Self

class LabelGroupOutput(BaseModel):
    """
    A label group (dimension) with its type and allowed values.
    """ # noqa: E501
    key: StrictStr
    description: Optional[StrictStr] = ''
    type: Optional[StrictStr] = 'value'
    optional: Optional[StrictBool] = True
    tag: Optional[StrictBool] = False
    values: Optional[List[LabelValue]] = None
    fields: Optional[Dict[str, MapFieldOutput]] = None
    __properties: ClassVar[List[str]] = ["key", "description", "type", "optional", "tag", "values", "fields"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['value', 'multi-values', 'text', 'map']):
            raise ValueError("must be one of enum values ('value', 'multi-values', 'text', 'map')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LabelGroupOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in values (list)
        _items = []
        if self.values:
            for _item_values in self.values:
                if _item_values:
                    _items.append(_item_values.to_dict())
            _dict['values'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in fields (dict)
        _field_dict = {}
        if self.fields:
            for _key_fields in self.fields:
                if self.fields[_key_fields]:
                    _field_dict[_key_fields] = self.fields[_key_fields].to_dict()
            _dict['fields'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LabelGroupOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "key": obj.get("key"),
            "description": obj.get("description") if obj.get("description") is not None else '',
            "type": obj.get("type") if obj.get("type") is not None else 'value',
            "optional": obj.get("optional") if obj.get("optional") is not None else True,
            "tag": obj.get("tag") if obj.get("tag") is not None else False,
            "values": [LabelValue.from_dict(_item) for _item in obj["values"]] if obj.get("values") is not None else None,
            "fields": dict(
                (_k, MapFieldOutput.from_dict(_v))
                for _k, _v in obj["fields"].items()
            )
            if obj.get("fields") is not None
            else None
        })
        return _obj


