# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.8.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.mental_model_refresh_overrides_tag_groups_inner import MentalModelRefreshOverridesTagGroupsInner
from typing import Optional, Set
from typing_extensions import Self

class MentalModelRefreshOverrides(BaseModel):
    """
    Per-run overrides for a mental model refresh.  Only meaningful for the dry run, which uses them to A/B a candidate configuration against the model's stored one without editing the model. Every field defaults to None, meaning \"use the model's stored setting\".
    """ # noqa: E501
    mode: Optional[StrictStr] = None
    source_query: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    tags_match: Optional[StrictStr] = None
    tag_groups: Optional[List[MentalModelRefreshOverridesTagGroupsInner]] = None
    fact_types: Optional[List[StrictStr]] = None
    exclude_mental_models: Optional[StrictBool] = None
    max_tokens: Optional[StrictInt] = None
    include_chunks: Optional[StrictBool] = None
    recall_max_tokens: Optional[StrictInt] = None
    recall_chunks_max_tokens: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["mode", "source_query", "tags", "tags_match", "tag_groups", "fact_types", "exclude_mental_models", "max_tokens", "include_chunks", "recall_max_tokens", "recall_chunks_max_tokens"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['full', 'delta']):
            raise ValueError("must be one of enum values ('full', 'delta')")
        return value

    @field_validator('tags_match')
    def tags_match_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['any', 'all', 'any_strict', 'all_strict', 'exact']):
            raise ValueError("must be one of enum values ('any', 'all', 'any_strict', 'all_strict', 'exact')")
        return value

    @field_validator('fact_types')
    def fact_types_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['world', 'experience', 'observation']):
                raise ValueError("each list item must be one of ('world', 'experience', 'observation')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MentalModelRefreshOverrides from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tag_groups (list)
        _items = []
        if self.tag_groups:
            for _item_tag_groups in self.tag_groups:
                if _item_tag_groups:
                    _items.append(_item_tag_groups.to_dict())
            _dict['tag_groups'] = _items
        # set to None if mode (nullable) is None
        # and model_fields_set contains the field
        if self.mode is None and "mode" in self.model_fields_set:
            _dict['mode'] = None

        # set to None if source_query (nullable) is None
        # and model_fields_set contains the field
        if self.source_query is None and "source_query" in self.model_fields_set:
            _dict['source_query'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if tags_match (nullable) is None
        # and model_fields_set contains the field
        if self.tags_match is None and "tags_match" in self.model_fields_set:
            _dict['tags_match'] = None

        # set to None if tag_groups (nullable) is None
        # and model_fields_set contains the field
        if self.tag_groups is None and "tag_groups" in self.model_fields_set:
            _dict['tag_groups'] = None

        # set to None if fact_types (nullable) is None
        # and model_fields_set contains the field
        if self.fact_types is None and "fact_types" in self.model_fields_set:
            _dict['fact_types'] = None

        # set to None if exclude_mental_models (nullable) is None
        # and model_fields_set contains the field
        if self.exclude_mental_models is None and "exclude_mental_models" in self.model_fields_set:
            _dict['exclude_mental_models'] = None

        # set to None if max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.max_tokens is None and "max_tokens" in self.model_fields_set:
            _dict['max_tokens'] = None

        # set to None if include_chunks (nullable) is None
        # and model_fields_set contains the field
        if self.include_chunks is None and "include_chunks" in self.model_fields_set:
            _dict['include_chunks'] = None

        # set to None if recall_max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.recall_max_tokens is None and "recall_max_tokens" in self.model_fields_set:
            _dict['recall_max_tokens'] = None

        # set to None if recall_chunks_max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.recall_chunks_max_tokens is None and "recall_chunks_max_tokens" in self.model_fields_set:
            _dict['recall_chunks_max_tokens'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MentalModelRefreshOverrides from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mode": obj.get("mode"),
            "source_query": obj.get("source_query"),
            "tags": obj.get("tags"),
            "tags_match": obj.get("tags_match"),
            "tag_groups": [MentalModelRefreshOverridesTagGroupsInner.from_dict(_item) for _item in obj["tag_groups"]] if obj.get("tag_groups") is not None else None,
            "fact_types": obj.get("fact_types"),
            "exclude_mental_models": obj.get("exclude_mental_models"),
            "max_tokens": obj.get("max_tokens"),
            "include_chunks": obj.get("include_chunks"),
            "recall_max_tokens": obj.get("recall_max_tokens"),
            "recall_chunks_max_tokens": obj.get("recall_chunks_max_tokens")
        })
        return _obj


