# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.8.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MentalModelTraceToolCall(BaseModel):
    """
    One reflect tool call made during a refresh.  Tool *outputs* are deliberately reduced to ``result_count``: a refresh trace is persisted on the model row and re-read on every fetch, so embedding full recall payloads would bloat it without bound. Raw prompts and responses are available separately via LLM request tracing.
    """ # noqa: E501
    tool: StrictStr = Field(description="Tool name: recall, search_observations, get_mental_model, expand, …")
    reason: Optional[StrictStr] = None
    input: Optional[Dict[str, Any]] = Field(default=None, description="Tool input parameters.")
    result_count: Optional[StrictInt] = None
    duration_ms: StrictInt = Field(description="Execution time in milliseconds.")
    iteration: Optional[StrictInt] = Field(default=0, description="Agent loop iteration (1-based) this call belongs to.")
    __properties: ClassVar[List[str]] = ["tool", "reason", "input", "result_count", "duration_ms", "iteration"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MentalModelTraceToolCall from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if result_count (nullable) is None
        # and model_fields_set contains the field
        if self.result_count is None and "result_count" in self.model_fields_set:
            _dict['result_count'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MentalModelTraceToolCall from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tool": obj.get("tool"),
            "reason": obj.get("reason"),
            "input": obj.get("input"),
            "result_count": obj.get("result_count"),
            "duration_ms": obj.get("duration_ms"),
            "iteration": obj.get("iteration") if obj.get("iteration") is not None else 0
        })
        return _obj


