# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.llm_call_trace import LLMCallTrace
from hindsight_client_api.models.mental_model_delta_operations import MentalModelDeltaOperations
from hindsight_client_api.models.mental_model_trace_tool_call import MentalModelTraceToolCall
from hindsight_client_api.models.token_usage import TokenUsage
from typing import Optional, Set
from typing_extensions import Self

class MentalModelRefreshTrace(BaseModel):
    """
    Execution trace of a mental model refresh, recorded when trigger.keep_trace is on.  Deliberately shaped like reflect's trace — the calls the agent made, plus the refresh-specific decision — and nothing more. This is persisted on the mental model row and re-read on every fetch, so anything derivable from elsewhere is left out: the evidence lives in ``reflect_response.based_on``, and the resolved scope and snapshot window are reported by the dry run.
    """ # noqa: E501
    recorded_at: Optional[datetime] = None
    effective_mode: StrictStr = Field(description="Whether the refresh ran as full or delta.")
    mode_fallback_reason: Optional[StrictStr] = None
    outcome: StrictStr = Field(description="What the refresh did with the document.")
    tool_calls: Optional[List[MentalModelTraceToolCall]] = Field(default=None, description="Reflect tool calls made during the refresh.")
    llm_calls: Optional[List[LLMCallTrace]] = Field(default=None, description="LLM calls made during the refresh.")
    delta_operations: Optional[MentalModelDeltaOperations] = None
    usage: Optional[TokenUsage] = None
    duration_ms: Optional[StrictInt] = Field(default=0, description="Wall-clock duration of the refresh.")
    warnings: Optional[List[StrictStr]] = Field(default=None, description="Conditions worth a human's attention, in plain language.")
    __properties: ClassVar[List[str]] = ["recorded_at", "effective_mode", "mode_fallback_reason", "outcome", "tool_calls", "llm_calls", "delta_operations", "usage", "duration_ms", "warnings"]

    @field_validator('effective_mode')
    def effective_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['full', 'delta']):
            raise ValueError("must be one of enum values ('full', 'delta')")
        return value

    @field_validator('mode_fallback_reason')
    def mode_fallback_reason_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['no_baseline_content', 'source_query_changed', 'structured_doc_unreadable', 'delta_ops_failed', 'delta_ops_all_skipped']):
            raise ValueError("must be one of enum values ('no_baseline_content', 'source_query_changed', 'structured_doc_unreadable', 'delta_ops_failed', 'delta_ops_all_skipped')")
        return value

    @field_validator('outcome')
    def outcome_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['content_written', 'content_preserved_no_new_facts', 'refresh_failed_empty_candidate', 'refresh_failed_delta_not_applied']):
            raise ValueError("must be one of enum values ('content_written', 'content_preserved_no_new_facts', 'refresh_failed_empty_candidate', 'refresh_failed_delta_not_applied')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MentalModelRefreshTrace from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tool_calls (list)
        _items = []
        if self.tool_calls:
            for _item_tool_calls in self.tool_calls:
                if _item_tool_calls:
                    _items.append(_item_tool_calls.to_dict())
            _dict['tool_calls'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in llm_calls (list)
        _items = []
        if self.llm_calls:
            for _item_llm_calls in self.llm_calls:
                if _item_llm_calls:
                    _items.append(_item_llm_calls.to_dict())
            _dict['llm_calls'] = _items
        # override the default output from pydantic by calling `to_dict()` of delta_operations
        if self.delta_operations:
            _dict['delta_operations'] = self.delta_operations.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # set to None if recorded_at (nullable) is None
        # and model_fields_set contains the field
        if self.recorded_at is None and "recorded_at" in self.model_fields_set:
            _dict['recorded_at'] = None

        # set to None if mode_fallback_reason (nullable) is None
        # and model_fields_set contains the field
        if self.mode_fallback_reason is None and "mode_fallback_reason" in self.model_fields_set:
            _dict['mode_fallback_reason'] = None

        # set to None if delta_operations (nullable) is None
        # and model_fields_set contains the field
        if self.delta_operations is None and "delta_operations" in self.model_fields_set:
            _dict['delta_operations'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MentalModelRefreshTrace from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "recorded_at": obj.get("recorded_at"),
            "effective_mode": obj.get("effective_mode"),
            "mode_fallback_reason": obj.get("mode_fallback_reason"),
            "outcome": obj.get("outcome"),
            "tool_calls": [MentalModelTraceToolCall.from_dict(_item) for _item in obj["tool_calls"]] if obj.get("tool_calls") is not None else None,
            "llm_calls": [LLMCallTrace.from_dict(_item) for _item in obj["llm_calls"]] if obj.get("llm_calls") is not None else None,
            "delta_operations": MentalModelDeltaOperations.from_dict(obj["delta_operations"]) if obj.get("delta_operations") is not None else None,
            "usage": TokenUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
            "duration_ms": obj.get("duration_ms") if obj.get("duration_ms") is not None else 0,
            "warnings": obj.get("warnings")
        })
        return _obj


