# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.budget import Budget
from hindsight_client_api.models.include_options import IncludeOptions
from hindsight_client_api.models.mental_model_trigger_input_tag_groups_inner import MentalModelTriggerInputTagGroupsInner
from hindsight_client_api.models.min_scores import MinScores
from typing import Optional, Set
from typing_extensions import Self

class RecallRequest(BaseModel):
    """
    Request model for recall endpoint.
    """ # noqa: E501
    query: StrictStr
    types: Optional[List[StrictStr]] = None
    prefer_observations: Optional[StrictBool] = Field(default=False, description="When recalling raw facts ('world'/'experience') together with 'observation', drop any raw fact that an observation in the results was consolidated from, so the observation supersedes it and you don't get duplicate content. The freed slots are backfilled with the next results, keeping the result count at the requested budget. Disabled by default; set to true to enable. No effect unless 'observation' and at least one raw type are both requested.")
    budget: Optional[Budget] = None
    max_tokens: Optional[StrictInt] = 4096
    trace: Optional[StrictBool] = False
    query_timestamp: Optional[StrictStr] = None
    include: Optional[IncludeOptions] = Field(default=None, description="Options for including additional data (entities are included by default)")
    tags: Optional[List[StrictStr]] = None
    tags_match: Optional[StrictStr] = Field(default='any', description="How to match tags: 'any' (OR, includes untagged), 'all' (AND, includes untagged), 'any_strict' (OR, excludes untagged), 'all_strict' (AND, excludes untagged), 'exact' (set-equality on the full scope, excludes untagged). With 'exact' and no tags (or []), the empty global scope is selected and only untagged memories match.")
    tag_groups: Optional[List[MentalModelTriggerInputTagGroupsInner]] = None
    min_scores: Optional[MinScores] = None
    __properties: ClassVar[List[str]] = ["query", "types", "prefer_observations", "budget", "max_tokens", "trace", "query_timestamp", "include", "tags", "tags_match", "tag_groups", "min_scores"]

    @field_validator('tags_match')
    def tags_match_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['any', 'all', 'any_strict', 'all_strict', 'exact']):
            raise ValueError("must be one of enum values ('any', 'all', 'any_strict', 'all_strict', 'exact')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecallRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of include
        if self.include:
            _dict['include'] = self.include.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tag_groups (list)
        _items = []
        if self.tag_groups:
            for _item_tag_groups in self.tag_groups:
                if _item_tag_groups:
                    _items.append(_item_tag_groups.to_dict())
            _dict['tag_groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of min_scores
        if self.min_scores:
            _dict['min_scores'] = self.min_scores.to_dict()
        # set to None if types (nullable) is None
        # and model_fields_set contains the field
        if self.types is None and "types" in self.model_fields_set:
            _dict['types'] = None

        # set to None if query_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.query_timestamp is None and "query_timestamp" in self.model_fields_set:
            _dict['query_timestamp'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if tag_groups (nullable) is None
        # and model_fields_set contains the field
        if self.tag_groups is None and "tag_groups" in self.model_fields_set:
            _dict['tag_groups'] = None

        # set to None if min_scores (nullable) is None
        # and model_fields_set contains the field
        if self.min_scores is None and "min_scores" in self.model_fields_set:
            _dict['min_scores'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecallRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "types": obj.get("types"),
            "prefer_observations": obj.get("prefer_observations") if obj.get("prefer_observations") is not None else False,
            "budget": obj.get("budget"),
            "max_tokens": obj.get("max_tokens") if obj.get("max_tokens") is not None else 4096,
            "trace": obj.get("trace") if obj.get("trace") is not None else False,
            "query_timestamp": obj.get("query_timestamp"),
            "include": IncludeOptions.from_dict(obj["include"]) if obj.get("include") is not None else None,
            "tags": obj.get("tags"),
            "tags_match": obj.get("tags_match") if obj.get("tags_match") is not None else 'any',
            "tag_groups": [MentalModelTriggerInputTagGroupsInner.from_dict(_item) for _item in obj["tag_groups"]] if obj.get("tag_groups") is not None else None,
            "min_scores": MinScores.from_dict(obj["min_scores"]) if obj.get("min_scores") is not None else None
        })
        return _obj


