/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BankListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BankListResponse{}

// BankListResponse Response model for listing banks, one page at a time.
type BankListResponse struct {
	Banks []BankListItem `json:"banks"`
	// Total number of banks visible to the caller, ignoring `limit`/`offset`.
	Total int32 `json:"total"`
	Limit int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type _BankListResponse BankListResponse

// NewBankListResponse instantiates a new BankListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankListResponse(banks []BankListItem, total int32, limit int32, offset int32) *BankListResponse {
	this := BankListResponse{}
	this.Banks = banks
	this.Total = total
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewBankListResponseWithDefaults instantiates a new BankListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankListResponseWithDefaults() *BankListResponse {
	this := BankListResponse{}
	return &this
}

// GetBanks returns the Banks field value
func (o *BankListResponse) GetBanks() []BankListItem {
	if o == nil {
		var ret []BankListItem
		return ret
	}

	return o.Banks
}

// GetBanksOk returns a tuple with the Banks field value
// and a boolean to check if the value has been set.
func (o *BankListResponse) GetBanksOk() ([]BankListItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Banks, true
}

// SetBanks sets field value
func (o *BankListResponse) SetBanks(v []BankListItem) {
	o.Banks = v
}

// GetTotal returns the Total field value
func (o *BankListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *BankListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *BankListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetLimit returns the Limit field value
func (o *BankListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *BankListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *BankListResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *BankListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *BankListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *BankListResponse) SetOffset(v int32) {
	o.Offset = v
}

func (o BankListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BankListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["banks"] = o.Banks
	toSerialize["total"] = o.Total
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	return toSerialize, nil
}

func (o *BankListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"banks",
		"total",
		"limit",
		"offset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBankListResponse := _BankListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBankListResponse)

	if err != nil {
		return err
	}

	*o = BankListResponse(varBankListResponse)

	return err
}

type NullableBankListResponse struct {
	value *BankListResponse
	isSet bool
}

func (v NullableBankListResponse) Get() *BankListResponse {
	return v.value
}

func (v *NullableBankListResponse) Set(val *BankListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBankListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBankListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankListResponse(val *BankListResponse) *NullableBankListResponse {
	return &NullableBankListResponse{value: val, isSet: true}
}

func (v NullableBankListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


