/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the MinScores type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MinScores{}

// MinScores Optional per-stage score floors for recall (all inclusive, AND-ed).  ``semantic`` and ``keyword`` are **retrieval-level** cutoffs pushed into the SQL arms (overriding the global ``semantic_min_similarity`` / ``bm25_min_score`` config for this request), so they prune weak matches before fusion. ``reranker`` and ``final`` are **post-query** filters applied to the scored results after reranking. Any field left None imposes no floor; all-None (the default) means no score filtering.
type MinScores struct {
	Semantic NullableFloat32 `json:"semantic,omitempty"`
	Keyword NullableFloat32 `json:"keyword,omitempty"`
	Reranker NullableFloat32 `json:"reranker,omitempty"`
	Final NullableFloat32 `json:"final,omitempty"`
}

// NewMinScores instantiates a new MinScores object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMinScores() *MinScores {
	this := MinScores{}
	return &this
}

// NewMinScoresWithDefaults instantiates a new MinScores object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMinScoresWithDefaults() *MinScores {
	this := MinScores{}
	return &this
}

// GetSemantic returns the Semantic field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MinScores) GetSemantic() float32 {
	if o == nil || IsNil(o.Semantic.Get()) {
		var ret float32
		return ret
	}
	return *o.Semantic.Get()
}

// GetSemanticOk returns a tuple with the Semantic field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MinScores) GetSemanticOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Semantic.Get(), o.Semantic.IsSet()
}

// HasSemantic returns a boolean if a field has been set.
func (o *MinScores) HasSemantic() bool {
	if o != nil && o.Semantic.IsSet() {
		return true
	}

	return false
}

// SetSemantic gets a reference to the given NullableFloat32 and assigns it to the Semantic field.
func (o *MinScores) SetSemantic(v float32) {
	o.Semantic.Set(&v)
}
// SetSemanticNil sets the value for Semantic to be an explicit nil
func (o *MinScores) SetSemanticNil() {
	o.Semantic.Set(nil)
}

// UnsetSemantic ensures that no value is present for Semantic, not even an explicit nil
func (o *MinScores) UnsetSemantic() {
	o.Semantic.Unset()
}

// GetKeyword returns the Keyword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MinScores) GetKeyword() float32 {
	if o == nil || IsNil(o.Keyword.Get()) {
		var ret float32
		return ret
	}
	return *o.Keyword.Get()
}

// GetKeywordOk returns a tuple with the Keyword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MinScores) GetKeywordOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keyword.Get(), o.Keyword.IsSet()
}

// HasKeyword returns a boolean if a field has been set.
func (o *MinScores) HasKeyword() bool {
	if o != nil && o.Keyword.IsSet() {
		return true
	}

	return false
}

// SetKeyword gets a reference to the given NullableFloat32 and assigns it to the Keyword field.
func (o *MinScores) SetKeyword(v float32) {
	o.Keyword.Set(&v)
}
// SetKeywordNil sets the value for Keyword to be an explicit nil
func (o *MinScores) SetKeywordNil() {
	o.Keyword.Set(nil)
}

// UnsetKeyword ensures that no value is present for Keyword, not even an explicit nil
func (o *MinScores) UnsetKeyword() {
	o.Keyword.Unset()
}

// GetReranker returns the Reranker field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MinScores) GetReranker() float32 {
	if o == nil || IsNil(o.Reranker.Get()) {
		var ret float32
		return ret
	}
	return *o.Reranker.Get()
}

// GetRerankerOk returns a tuple with the Reranker field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MinScores) GetRerankerOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reranker.Get(), o.Reranker.IsSet()
}

// HasReranker returns a boolean if a field has been set.
func (o *MinScores) HasReranker() bool {
	if o != nil && o.Reranker.IsSet() {
		return true
	}

	return false
}

// SetReranker gets a reference to the given NullableFloat32 and assigns it to the Reranker field.
func (o *MinScores) SetReranker(v float32) {
	o.Reranker.Set(&v)
}
// SetRerankerNil sets the value for Reranker to be an explicit nil
func (o *MinScores) SetRerankerNil() {
	o.Reranker.Set(nil)
}

// UnsetReranker ensures that no value is present for Reranker, not even an explicit nil
func (o *MinScores) UnsetReranker() {
	o.Reranker.Unset()
}

// GetFinal returns the Final field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MinScores) GetFinal() float32 {
	if o == nil || IsNil(o.Final.Get()) {
		var ret float32
		return ret
	}
	return *o.Final.Get()
}

// GetFinalOk returns a tuple with the Final field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MinScores) GetFinalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Final.Get(), o.Final.IsSet()
}

// HasFinal returns a boolean if a field has been set.
func (o *MinScores) HasFinal() bool {
	if o != nil && o.Final.IsSet() {
		return true
	}

	return false
}

// SetFinal gets a reference to the given NullableFloat32 and assigns it to the Final field.
func (o *MinScores) SetFinal(v float32) {
	o.Final.Set(&v)
}
// SetFinalNil sets the value for Final to be an explicit nil
func (o *MinScores) SetFinalNil() {
	o.Final.Set(nil)
}

// UnsetFinal ensures that no value is present for Final, not even an explicit nil
func (o *MinScores) UnsetFinal() {
	o.Final.Unset()
}

func (o MinScores) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MinScores) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Semantic.IsSet() {
		toSerialize["semantic"] = o.Semantic.Get()
	}
	if o.Keyword.IsSet() {
		toSerialize["keyword"] = o.Keyword.Get()
	}
	if o.Reranker.IsSet() {
		toSerialize["reranker"] = o.Reranker.Get()
	}
	if o.Final.IsSet() {
		toSerialize["final"] = o.Final.Get()
	}
	return toSerialize, nil
}

type NullableMinScores struct {
	value *MinScores
	isSet bool
}

func (v NullableMinScores) Get() *MinScores {
	return v.value
}

func (v *NullableMinScores) Set(val *MinScores) {
	v.value = val
	v.isSet = true
}

func (v NullableMinScores) IsSet() bool {
	return v.isSet
}

func (v *NullableMinScores) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMinScores(val *MinScores) *NullableMinScores {
	return &NullableMinScores{value: val, isSet: true}
}

func (v NullableMinScores) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMinScores) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


