/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the MentalModelDeltaOperations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentalModelDeltaOperations{}

// MentalModelDeltaOperations Structured operations a delta refresh emitted against the existing document.
type MentalModelDeltaOperations struct {
	// Operations applied to the document, in order.
	Applied []map[string]interface{} `json:"applied,omitempty"`
	// Operations dropped as invalid, each with a reason.
	Skipped []map[string]interface{} `json:"skipped,omitempty"`
}

// NewMentalModelDeltaOperations instantiates a new MentalModelDeltaOperations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentalModelDeltaOperations() *MentalModelDeltaOperations {
	this := MentalModelDeltaOperations{}
	return &this
}

// NewMentalModelDeltaOperationsWithDefaults instantiates a new MentalModelDeltaOperations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentalModelDeltaOperationsWithDefaults() *MentalModelDeltaOperations {
	this := MentalModelDeltaOperations{}
	return &this
}

// GetApplied returns the Applied field value if set, zero value otherwise.
func (o *MentalModelDeltaOperations) GetApplied() []map[string]interface{} {
	if o == nil || IsNil(o.Applied) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Applied
}

// GetAppliedOk returns a tuple with the Applied field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelDeltaOperations) GetAppliedOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Applied) {
		return nil, false
	}
	return o.Applied, true
}

// HasApplied returns a boolean if a field has been set.
func (o *MentalModelDeltaOperations) HasApplied() bool {
	if o != nil && !IsNil(o.Applied) {
		return true
	}

	return false
}

// SetApplied gets a reference to the given []map[string]interface{} and assigns it to the Applied field.
func (o *MentalModelDeltaOperations) SetApplied(v []map[string]interface{}) {
	o.Applied = v
}

// GetSkipped returns the Skipped field value if set, zero value otherwise.
func (o *MentalModelDeltaOperations) GetSkipped() []map[string]interface{} {
	if o == nil || IsNil(o.Skipped) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Skipped
}

// GetSkippedOk returns a tuple with the Skipped field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelDeltaOperations) GetSkippedOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Skipped) {
		return nil, false
	}
	return o.Skipped, true
}

// HasSkipped returns a boolean if a field has been set.
func (o *MentalModelDeltaOperations) HasSkipped() bool {
	if o != nil && !IsNil(o.Skipped) {
		return true
	}

	return false
}

// SetSkipped gets a reference to the given []map[string]interface{} and assigns it to the Skipped field.
func (o *MentalModelDeltaOperations) SetSkipped(v []map[string]interface{}) {
	o.Skipped = v
}

func (o MentalModelDeltaOperations) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentalModelDeltaOperations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Applied) {
		toSerialize["applied"] = o.Applied
	}
	if !IsNil(o.Skipped) {
		toSerialize["skipped"] = o.Skipped
	}
	return toSerialize, nil
}

type NullableMentalModelDeltaOperations struct {
	value *MentalModelDeltaOperations
	isSet bool
}

func (v NullableMentalModelDeltaOperations) Get() *MentalModelDeltaOperations {
	return v.value
}

func (v *NullableMentalModelDeltaOperations) Set(val *MentalModelDeltaOperations) {
	v.value = val
	v.isSet = true
}

func (v NullableMentalModelDeltaOperations) IsSet() bool {
	return v.isSet
}

func (v *NullableMentalModelDeltaOperations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentalModelDeltaOperations(val *MentalModelDeltaOperations) *NullableMentalModelDeltaOperations {
	return &NullableMentalModelDeltaOperations{value: val, isSet: true}
}

func (v NullableMentalModelDeltaOperations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentalModelDeltaOperations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


