/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the UpdateNodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNodeRequest{}

// UpdateNodeRequest Rename/move a node and/or update a page's options. Each field applies only when present in the request body.
type UpdateNodeRequest struct {
	Name NullableString `json:"name,omitempty"`
	ParentId NullableString `json:"parent_id,omitempty"`
	SourceQuery NullableString `json:"source_query,omitempty"`
	Tags []string `json:"tags,omitempty"`
	MaxTokens NullableInt32 `json:"max_tokens,omitempty"`
	Trigger NullableMentalModelTriggerInput `json:"trigger,omitempty"`
}

// NewUpdateNodeRequest instantiates a new UpdateNodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNodeRequest() *UpdateNodeRequest {
	this := UpdateNodeRequest{}
	return &this
}

// NewUpdateNodeRequestWithDefaults instantiates a new UpdateNodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNodeRequestWithDefaults() *UpdateNodeRequest {
	this := UpdateNodeRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNodeRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNodeRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UpdateNodeRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UpdateNodeRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *UpdateNodeRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UpdateNodeRequest) UnsetName() {
	o.Name.Unset()
}

// GetParentId returns the ParentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNodeRequest) GetParentId() string {
	if o == nil || IsNil(o.ParentId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentId.Get()
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNodeRequest) GetParentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentId.Get(), o.ParentId.IsSet()
}

// HasParentId returns a boolean if a field has been set.
func (o *UpdateNodeRequest) HasParentId() bool {
	if o != nil && o.ParentId.IsSet() {
		return true
	}

	return false
}

// SetParentId gets a reference to the given NullableString and assigns it to the ParentId field.
func (o *UpdateNodeRequest) SetParentId(v string) {
	o.ParentId.Set(&v)
}
// SetParentIdNil sets the value for ParentId to be an explicit nil
func (o *UpdateNodeRequest) SetParentIdNil() {
	o.ParentId.Set(nil)
}

// UnsetParentId ensures that no value is present for ParentId, not even an explicit nil
func (o *UpdateNodeRequest) UnsetParentId() {
	o.ParentId.Unset()
}

// GetSourceQuery returns the SourceQuery field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNodeRequest) GetSourceQuery() string {
	if o == nil || IsNil(o.SourceQuery.Get()) {
		var ret string
		return ret
	}
	return *o.SourceQuery.Get()
}

// GetSourceQueryOk returns a tuple with the SourceQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNodeRequest) GetSourceQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceQuery.Get(), o.SourceQuery.IsSet()
}

// HasSourceQuery returns a boolean if a field has been set.
func (o *UpdateNodeRequest) HasSourceQuery() bool {
	if o != nil && o.SourceQuery.IsSet() {
		return true
	}

	return false
}

// SetSourceQuery gets a reference to the given NullableString and assigns it to the SourceQuery field.
func (o *UpdateNodeRequest) SetSourceQuery(v string) {
	o.SourceQuery.Set(&v)
}
// SetSourceQueryNil sets the value for SourceQuery to be an explicit nil
func (o *UpdateNodeRequest) SetSourceQueryNil() {
	o.SourceQuery.Set(nil)
}

// UnsetSourceQuery ensures that no value is present for SourceQuery, not even an explicit nil
func (o *UpdateNodeRequest) UnsetSourceQuery() {
	o.SourceQuery.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNodeRequest) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNodeRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *UpdateNodeRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *UpdateNodeRequest) SetTags(v []string) {
	o.Tags = v
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNodeRequest) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxTokens.Get()
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNodeRequest) GetMaxTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxTokens.Get(), o.MaxTokens.IsSet()
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *UpdateNodeRequest) HasMaxTokens() bool {
	if o != nil && o.MaxTokens.IsSet() {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given NullableInt32 and assigns it to the MaxTokens field.
func (o *UpdateNodeRequest) SetMaxTokens(v int32) {
	o.MaxTokens.Set(&v)
}
// SetMaxTokensNil sets the value for MaxTokens to be an explicit nil
func (o *UpdateNodeRequest) SetMaxTokensNil() {
	o.MaxTokens.Set(nil)
}

// UnsetMaxTokens ensures that no value is present for MaxTokens, not even an explicit nil
func (o *UpdateNodeRequest) UnsetMaxTokens() {
	o.MaxTokens.Unset()
}

// GetTrigger returns the Trigger field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNodeRequest) GetTrigger() MentalModelTriggerInput {
	if o == nil || IsNil(o.Trigger.Get()) {
		var ret MentalModelTriggerInput
		return ret
	}
	return *o.Trigger.Get()
}

// GetTriggerOk returns a tuple with the Trigger field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNodeRequest) GetTriggerOk() (*MentalModelTriggerInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Trigger.Get(), o.Trigger.IsSet()
}

// HasTrigger returns a boolean if a field has been set.
func (o *UpdateNodeRequest) HasTrigger() bool {
	if o != nil && o.Trigger.IsSet() {
		return true
	}

	return false
}

// SetTrigger gets a reference to the given NullableMentalModelTriggerInput and assigns it to the Trigger field.
func (o *UpdateNodeRequest) SetTrigger(v MentalModelTriggerInput) {
	o.Trigger.Set(&v)
}
// SetTriggerNil sets the value for Trigger to be an explicit nil
func (o *UpdateNodeRequest) SetTriggerNil() {
	o.Trigger.Set(nil)
}

// UnsetTrigger ensures that no value is present for Trigger, not even an explicit nil
func (o *UpdateNodeRequest) UnsetTrigger() {
	o.Trigger.Unset()
}

func (o UpdateNodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.ParentId.IsSet() {
		toSerialize["parent_id"] = o.ParentId.Get()
	}
	if o.SourceQuery.IsSet() {
		toSerialize["source_query"] = o.SourceQuery.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.MaxTokens.IsSet() {
		toSerialize["max_tokens"] = o.MaxTokens.Get()
	}
	if o.Trigger.IsSet() {
		toSerialize["trigger"] = o.Trigger.Get()
	}
	return toSerialize, nil
}

type NullableUpdateNodeRequest struct {
	value *UpdateNodeRequest
	isSet bool
}

func (v NullableUpdateNodeRequest) Get() *UpdateNodeRequest {
	return v.value
}

func (v *NullableUpdateNodeRequest) Set(val *UpdateNodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNodeRequest(val *UpdateNodeRequest) *NullableUpdateNodeRequest {
	return &NullableUpdateNodeRequest{value: val, isSet: true}
}

func (v NullableUpdateNodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


