/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LLMCallTrace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LLMCallTrace{}

// LLMCallTrace A single LLM call made during reflect.
type LLMCallTrace struct {
	// Call scope: agent_1, agent_2, final, etc.
	Scope string `json:"scope"`
	// Execution time in milliseconds
	DurationMs int32 `json:"duration_ms"`
}

type _LLMCallTrace LLMCallTrace

// NewLLMCallTrace instantiates a new LLMCallTrace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLLMCallTrace(scope string, durationMs int32) *LLMCallTrace {
	this := LLMCallTrace{}
	this.Scope = scope
	this.DurationMs = durationMs
	return &this
}

// NewLLMCallTraceWithDefaults instantiates a new LLMCallTrace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLLMCallTraceWithDefaults() *LLMCallTrace {
	this := LLMCallTrace{}
	return &this
}

// GetScope returns the Scope field value
func (o *LLMCallTrace) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *LLMCallTrace) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *LLMCallTrace) SetScope(v string) {
	o.Scope = v
}

// GetDurationMs returns the DurationMs field value
func (o *LLMCallTrace) GetDurationMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value
// and a boolean to check if the value has been set.
func (o *LLMCallTrace) GetDurationMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationMs, true
}

// SetDurationMs sets field value
func (o *LLMCallTrace) SetDurationMs(v int32) {
	o.DurationMs = v
}

func (o LLMCallTrace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LLMCallTrace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scope"] = o.Scope
	toSerialize["duration_ms"] = o.DurationMs
	return toSerialize, nil
}

func (o *LLMCallTrace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scope",
		"duration_ms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLLMCallTrace := _LLMCallTrace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLLMCallTrace)

	if err != nil {
		return err
	}

	*o = LLMCallTrace(varLLMCallTrace)

	return err
}

type NullableLLMCallTrace struct {
	value *LLMCallTrace
	isSet bool
}

func (v NullableLLMCallTrace) Get() *LLMCallTrace {
	return v.value
}

func (v *NullableLLMCallTrace) Set(val *LLMCallTrace) {
	v.value = val
	v.isSet = true
}

func (v NullableLLMCallTrace) IsSet() bool {
	return v.isSet
}

func (v *NullableLLMCallTrace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLLMCallTrace(val *LLMCallTrace) *NullableLLMCallTrace {
	return &NullableLLMCallTrace{value: val, isSet: true}
}

func (v NullableLLMCallTrace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLLMCallTrace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


