/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the MapFieldInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MapFieldInput{}

// MapFieldInput A field within a map-type entity label group. Supports recursion via type='map'.
type MapFieldInput struct {
	Type *string `json:"type,omitempty"`
	Description *string `json:"description,omitempty"`
	Values []LabelValue `json:"values,omitempty"`
	Fields map[string]MapFieldInput `json:"fields,omitempty"`
}

// NewMapFieldInput instantiates a new MapFieldInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMapFieldInput() *MapFieldInput {
	this := MapFieldInput{}
	var type_ string = "text"
	this.Type = &type_
	var description string = ""
	this.Description = &description
	return &this
}

// NewMapFieldInputWithDefaults instantiates a new MapFieldInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMapFieldInputWithDefaults() *MapFieldInput {
	this := MapFieldInput{}
	var type_ string = "text"
	this.Type = &type_
	var description string = ""
	this.Description = &description
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *MapFieldInput) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapFieldInput) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *MapFieldInput) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *MapFieldInput) SetType(v string) {
	o.Type = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MapFieldInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapFieldInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MapFieldInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MapFieldInput) SetDescription(v string) {
	o.Description = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *MapFieldInput) GetValues() []LabelValue {
	if o == nil || IsNil(o.Values) {
		var ret []LabelValue
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapFieldInput) GetValuesOk() ([]LabelValue, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *MapFieldInput) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []LabelValue and assigns it to the Values field.
func (o *MapFieldInput) SetValues(v []LabelValue) {
	o.Values = v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *MapFieldInput) GetFields() map[string]MapFieldInput {
	if o == nil || IsNil(o.Fields) {
		var ret map[string]MapFieldInput
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapFieldInput) GetFieldsOk() (map[string]MapFieldInput, bool) {
	if o == nil || IsNil(o.Fields) {
		return map[string]MapFieldInput{}, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *MapFieldInput) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given map[string]MapFieldInput and assigns it to the Fields field.
func (o *MapFieldInput) SetFields(v map[string]MapFieldInput) {
	o.Fields = v
}

func (o MapFieldInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MapFieldInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	return toSerialize, nil
}

type NullableMapFieldInput struct {
	value *MapFieldInput
	isSet bool
}

func (v NullableMapFieldInput) Get() *MapFieldInput {
	return v.value
}

func (v *NullableMapFieldInput) Set(val *MapFieldInput) {
	v.value = val
	v.isSet = true
}

func (v NullableMapFieldInput) IsSet() bool {
	return v.isSet
}

func (v *NullableMapFieldInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMapFieldInput(val *MapFieldInput) *NullableMapFieldInput {
	return &NullableMapFieldInput{value: val, isSet: true}
}

func (v NullableMapFieldInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMapFieldInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


