/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MentalModelRefreshTrace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentalModelRefreshTrace{}

// MentalModelRefreshTrace Execution trace of a mental model refresh, recorded when trigger.keep_trace is on.  Deliberately shaped like reflect's trace — the calls the agent made, plus the refresh-specific decision — and nothing more. This is persisted on the mental model row and re-read on every fetch, so anything derivable from elsewhere is left out: the evidence lives in ``reflect_response.based_on``, and the resolved scope and snapshot window are reported by the dry run.
type MentalModelRefreshTrace struct {
	RecordedAt NullableTime `json:"recorded_at,omitempty"`
	// Whether the refresh ran as full or delta.
	EffectiveMode string `json:"effective_mode"`
	ModeFallbackReason NullableString `json:"mode_fallback_reason,omitempty"`
	// What the refresh did with the document.
	Outcome string `json:"outcome"`
	// Reflect tool calls made during the refresh.
	ToolCalls []MentalModelTraceToolCall `json:"tool_calls,omitempty"`
	// LLM calls made during the refresh.
	LlmCalls []LLMCallTrace `json:"llm_calls,omitempty"`
	DeltaOperations NullableMentalModelDeltaOperations `json:"delta_operations,omitempty"`
	Usage NullableTokenUsage `json:"usage,omitempty"`
	// Wall-clock duration of the refresh.
	DurationMs *int32 `json:"duration_ms,omitempty"`
	// Conditions worth a human's attention, in plain language.
	Warnings []string `json:"warnings,omitempty"`
}

type _MentalModelRefreshTrace MentalModelRefreshTrace

// NewMentalModelRefreshTrace instantiates a new MentalModelRefreshTrace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentalModelRefreshTrace(effectiveMode string, outcome string) *MentalModelRefreshTrace {
	this := MentalModelRefreshTrace{}
	this.EffectiveMode = effectiveMode
	this.Outcome = outcome
	var durationMs int32 = 0
	this.DurationMs = &durationMs
	return &this
}

// NewMentalModelRefreshTraceWithDefaults instantiates a new MentalModelRefreshTrace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentalModelRefreshTraceWithDefaults() *MentalModelRefreshTrace {
	this := MentalModelRefreshTrace{}
	var durationMs int32 = 0
	this.DurationMs = &durationMs
	return &this
}

// GetRecordedAt returns the RecordedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshTrace) GetRecordedAt() time.Time {
	if o == nil || IsNil(o.RecordedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RecordedAt.Get()
}

// GetRecordedAtOk returns a tuple with the RecordedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshTrace) GetRecordedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecordedAt.Get(), o.RecordedAt.IsSet()
}

// HasRecordedAt returns a boolean if a field has been set.
func (o *MentalModelRefreshTrace) HasRecordedAt() bool {
	if o != nil && o.RecordedAt.IsSet() {
		return true
	}

	return false
}

// SetRecordedAt gets a reference to the given NullableTime and assigns it to the RecordedAt field.
func (o *MentalModelRefreshTrace) SetRecordedAt(v time.Time) {
	o.RecordedAt.Set(&v)
}
// SetRecordedAtNil sets the value for RecordedAt to be an explicit nil
func (o *MentalModelRefreshTrace) SetRecordedAtNil() {
	o.RecordedAt.Set(nil)
}

// UnsetRecordedAt ensures that no value is present for RecordedAt, not even an explicit nil
func (o *MentalModelRefreshTrace) UnsetRecordedAt() {
	o.RecordedAt.Unset()
}

// GetEffectiveMode returns the EffectiveMode field value
func (o *MentalModelRefreshTrace) GetEffectiveMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EffectiveMode
}

// GetEffectiveModeOk returns a tuple with the EffectiveMode field value
// and a boolean to check if the value has been set.
func (o *MentalModelRefreshTrace) GetEffectiveModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveMode, true
}

// SetEffectiveMode sets field value
func (o *MentalModelRefreshTrace) SetEffectiveMode(v string) {
	o.EffectiveMode = v
}

// GetModeFallbackReason returns the ModeFallbackReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshTrace) GetModeFallbackReason() string {
	if o == nil || IsNil(o.ModeFallbackReason.Get()) {
		var ret string
		return ret
	}
	return *o.ModeFallbackReason.Get()
}

// GetModeFallbackReasonOk returns a tuple with the ModeFallbackReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshTrace) GetModeFallbackReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModeFallbackReason.Get(), o.ModeFallbackReason.IsSet()
}

// HasModeFallbackReason returns a boolean if a field has been set.
func (o *MentalModelRefreshTrace) HasModeFallbackReason() bool {
	if o != nil && o.ModeFallbackReason.IsSet() {
		return true
	}

	return false
}

// SetModeFallbackReason gets a reference to the given NullableString and assigns it to the ModeFallbackReason field.
func (o *MentalModelRefreshTrace) SetModeFallbackReason(v string) {
	o.ModeFallbackReason.Set(&v)
}
// SetModeFallbackReasonNil sets the value for ModeFallbackReason to be an explicit nil
func (o *MentalModelRefreshTrace) SetModeFallbackReasonNil() {
	o.ModeFallbackReason.Set(nil)
}

// UnsetModeFallbackReason ensures that no value is present for ModeFallbackReason, not even an explicit nil
func (o *MentalModelRefreshTrace) UnsetModeFallbackReason() {
	o.ModeFallbackReason.Unset()
}

// GetOutcome returns the Outcome field value
func (o *MentalModelRefreshTrace) GetOutcome() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value
// and a boolean to check if the value has been set.
func (o *MentalModelRefreshTrace) GetOutcomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Outcome, true
}

// SetOutcome sets field value
func (o *MentalModelRefreshTrace) SetOutcome(v string) {
	o.Outcome = v
}

// GetToolCalls returns the ToolCalls field value if set, zero value otherwise.
func (o *MentalModelRefreshTrace) GetToolCalls() []MentalModelTraceToolCall {
	if o == nil || IsNil(o.ToolCalls) {
		var ret []MentalModelTraceToolCall
		return ret
	}
	return o.ToolCalls
}

// GetToolCallsOk returns a tuple with the ToolCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelRefreshTrace) GetToolCallsOk() ([]MentalModelTraceToolCall, bool) {
	if o == nil || IsNil(o.ToolCalls) {
		return nil, false
	}
	return o.ToolCalls, true
}

// HasToolCalls returns a boolean if a field has been set.
func (o *MentalModelRefreshTrace) HasToolCalls() bool {
	if o != nil && !IsNil(o.ToolCalls) {
		return true
	}

	return false
}

// SetToolCalls gets a reference to the given []MentalModelTraceToolCall and assigns it to the ToolCalls field.
func (o *MentalModelRefreshTrace) SetToolCalls(v []MentalModelTraceToolCall) {
	o.ToolCalls = v
}

// GetLlmCalls returns the LlmCalls field value if set, zero value otherwise.
func (o *MentalModelRefreshTrace) GetLlmCalls() []LLMCallTrace {
	if o == nil || IsNil(o.LlmCalls) {
		var ret []LLMCallTrace
		return ret
	}
	return o.LlmCalls
}

// GetLlmCallsOk returns a tuple with the LlmCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelRefreshTrace) GetLlmCallsOk() ([]LLMCallTrace, bool) {
	if o == nil || IsNil(o.LlmCalls) {
		return nil, false
	}
	return o.LlmCalls, true
}

// HasLlmCalls returns a boolean if a field has been set.
func (o *MentalModelRefreshTrace) HasLlmCalls() bool {
	if o != nil && !IsNil(o.LlmCalls) {
		return true
	}

	return false
}

// SetLlmCalls gets a reference to the given []LLMCallTrace and assigns it to the LlmCalls field.
func (o *MentalModelRefreshTrace) SetLlmCalls(v []LLMCallTrace) {
	o.LlmCalls = v
}

// GetDeltaOperations returns the DeltaOperations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshTrace) GetDeltaOperations() MentalModelDeltaOperations {
	if o == nil || IsNil(o.DeltaOperations.Get()) {
		var ret MentalModelDeltaOperations
		return ret
	}
	return *o.DeltaOperations.Get()
}

// GetDeltaOperationsOk returns a tuple with the DeltaOperations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshTrace) GetDeltaOperationsOk() (*MentalModelDeltaOperations, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeltaOperations.Get(), o.DeltaOperations.IsSet()
}

// HasDeltaOperations returns a boolean if a field has been set.
func (o *MentalModelRefreshTrace) HasDeltaOperations() bool {
	if o != nil && o.DeltaOperations.IsSet() {
		return true
	}

	return false
}

// SetDeltaOperations gets a reference to the given NullableMentalModelDeltaOperations and assigns it to the DeltaOperations field.
func (o *MentalModelRefreshTrace) SetDeltaOperations(v MentalModelDeltaOperations) {
	o.DeltaOperations.Set(&v)
}
// SetDeltaOperationsNil sets the value for DeltaOperations to be an explicit nil
func (o *MentalModelRefreshTrace) SetDeltaOperationsNil() {
	o.DeltaOperations.Set(nil)
}

// UnsetDeltaOperations ensures that no value is present for DeltaOperations, not even an explicit nil
func (o *MentalModelRefreshTrace) UnsetDeltaOperations() {
	o.DeltaOperations.Unset()
}

// GetUsage returns the Usage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshTrace) GetUsage() TokenUsage {
	if o == nil || IsNil(o.Usage.Get()) {
		var ret TokenUsage
		return ret
	}
	return *o.Usage.Get()
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshTrace) GetUsageOk() (*TokenUsage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Usage.Get(), o.Usage.IsSet()
}

// HasUsage returns a boolean if a field has been set.
func (o *MentalModelRefreshTrace) HasUsage() bool {
	if o != nil && o.Usage.IsSet() {
		return true
	}

	return false
}

// SetUsage gets a reference to the given NullableTokenUsage and assigns it to the Usage field.
func (o *MentalModelRefreshTrace) SetUsage(v TokenUsage) {
	o.Usage.Set(&v)
}
// SetUsageNil sets the value for Usage to be an explicit nil
func (o *MentalModelRefreshTrace) SetUsageNil() {
	o.Usage.Set(nil)
}

// UnsetUsage ensures that no value is present for Usage, not even an explicit nil
func (o *MentalModelRefreshTrace) UnsetUsage() {
	o.Usage.Unset()
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise.
func (o *MentalModelRefreshTrace) GetDurationMs() int32 {
	if o == nil || IsNil(o.DurationMs) {
		var ret int32
		return ret
	}
	return *o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelRefreshTrace) GetDurationMsOk() (*int32, bool) {
	if o == nil || IsNil(o.DurationMs) {
		return nil, false
	}
	return o.DurationMs, true
}

// HasDurationMs returns a boolean if a field has been set.
func (o *MentalModelRefreshTrace) HasDurationMs() bool {
	if o != nil && !IsNil(o.DurationMs) {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given int32 and assigns it to the DurationMs field.
func (o *MentalModelRefreshTrace) SetDurationMs(v int32) {
	o.DurationMs = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *MentalModelRefreshTrace) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelRefreshTrace) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *MentalModelRefreshTrace) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *MentalModelRefreshTrace) SetWarnings(v []string) {
	o.Warnings = v
}

func (o MentalModelRefreshTrace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentalModelRefreshTrace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.RecordedAt.IsSet() {
		toSerialize["recorded_at"] = o.RecordedAt.Get()
	}
	toSerialize["effective_mode"] = o.EffectiveMode
	if o.ModeFallbackReason.IsSet() {
		toSerialize["mode_fallback_reason"] = o.ModeFallbackReason.Get()
	}
	toSerialize["outcome"] = o.Outcome
	if !IsNil(o.ToolCalls) {
		toSerialize["tool_calls"] = o.ToolCalls
	}
	if !IsNil(o.LlmCalls) {
		toSerialize["llm_calls"] = o.LlmCalls
	}
	if o.DeltaOperations.IsSet() {
		toSerialize["delta_operations"] = o.DeltaOperations.Get()
	}
	if o.Usage.IsSet() {
		toSerialize["usage"] = o.Usage.Get()
	}
	if !IsNil(o.DurationMs) {
		toSerialize["duration_ms"] = o.DurationMs
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

func (o *MentalModelRefreshTrace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"effective_mode",
		"outcome",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMentalModelRefreshTrace := _MentalModelRefreshTrace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMentalModelRefreshTrace)

	if err != nil {
		return err
	}

	*o = MentalModelRefreshTrace(varMentalModelRefreshTrace)

	return err
}

type NullableMentalModelRefreshTrace struct {
	value *MentalModelRefreshTrace
	isSet bool
}

func (v NullableMentalModelRefreshTrace) Get() *MentalModelRefreshTrace {
	return v.value
}

func (v *NullableMentalModelRefreshTrace) Set(val *MentalModelRefreshTrace) {
	v.value = val
	v.isSet = true
}

func (v NullableMentalModelRefreshTrace) IsSet() bool {
	return v.isSet
}

func (v *NullableMentalModelRefreshTrace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentalModelRefreshTrace(val *MentalModelRefreshTrace) *NullableMentalModelRefreshTrace {
	return &NullableMentalModelRefreshTrace{value: val, isSet: true}
}

func (v NullableMentalModelRefreshTrace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentalModelRefreshTrace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


