/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteOperationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteOperationResponse{}

// DeleteOperationResponse Response model for delete operation endpoint.
type DeleteOperationResponse struct {
	Success bool `json:"success"`
	Message string `json:"message"`
	OperationId string `json:"operation_id"`
}

type _DeleteOperationResponse DeleteOperationResponse

// NewDeleteOperationResponse instantiates a new DeleteOperationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteOperationResponse(success bool, message string, operationId string) *DeleteOperationResponse {
	this := DeleteOperationResponse{}
	this.Success = success
	this.Message = message
	this.OperationId = operationId
	return &this
}

// NewDeleteOperationResponseWithDefaults instantiates a new DeleteOperationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteOperationResponseWithDefaults() *DeleteOperationResponse {
	this := DeleteOperationResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *DeleteOperationResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *DeleteOperationResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *DeleteOperationResponse) SetSuccess(v bool) {
	o.Success = v
}

// GetMessage returns the Message field value
func (o *DeleteOperationResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *DeleteOperationResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *DeleteOperationResponse) SetMessage(v string) {
	o.Message = v
}

// GetOperationId returns the OperationId field value
func (o *DeleteOperationResponse) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *DeleteOperationResponse) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *DeleteOperationResponse) SetOperationId(v string) {
	o.OperationId = v
}

func (o DeleteOperationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteOperationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["message"] = o.Message
	toSerialize["operation_id"] = o.OperationId
	return toSerialize, nil
}

func (o *DeleteOperationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"message",
		"operation_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteOperationResponse := _DeleteOperationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteOperationResponse)

	if err != nil {
		return err
	}

	*o = DeleteOperationResponse(varDeleteOperationResponse)

	return err
}

type NullableDeleteOperationResponse struct {
	value *DeleteOperationResponse
	isSet bool
}

func (v NullableDeleteOperationResponse) Get() *DeleteOperationResponse {
	return v.value
}

func (v *NullableDeleteOperationResponse) Set(val *DeleteOperationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteOperationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteOperationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteOperationResponse(val *DeleteOperationResponse) *NullableDeleteOperationResponse {
	return &NullableDeleteOperationResponse{value: val, isSet: true}
}

func (v NullableDeleteOperationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteOperationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


