/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LabelGroupInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelGroupInput{}

// LabelGroupInput A label group (dimension) with its type and allowed values.
type LabelGroupInput struct {
	Key string `json:"key"`
	Description *string `json:"description,omitempty"`
	Type *string `json:"type,omitempty"`
	Optional *bool `json:"optional,omitempty"`
	Tag *bool `json:"tag,omitempty"`
	Values []LabelValue `json:"values,omitempty"`
	Fields map[string]MapFieldInput `json:"fields,omitempty"`
}

type _LabelGroupInput LabelGroupInput

// NewLabelGroupInput instantiates a new LabelGroupInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelGroupInput(key string) *LabelGroupInput {
	this := LabelGroupInput{}
	this.Key = key
	var description string = ""
	this.Description = &description
	var type_ string = "value"
	this.Type = &type_
	var optional bool = true
	this.Optional = &optional
	var tag bool = false
	this.Tag = &tag
	return &this
}

// NewLabelGroupInputWithDefaults instantiates a new LabelGroupInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelGroupInputWithDefaults() *LabelGroupInput {
	this := LabelGroupInput{}
	var description string = ""
	this.Description = &description
	var type_ string = "value"
	this.Type = &type_
	var optional bool = true
	this.Optional = &optional
	var tag bool = false
	this.Tag = &tag
	return &this
}

// GetKey returns the Key field value
func (o *LabelGroupInput) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *LabelGroupInput) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *LabelGroupInput) SetKey(v string) {
	o.Key = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *LabelGroupInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelGroupInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *LabelGroupInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *LabelGroupInput) SetDescription(v string) {
	o.Description = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *LabelGroupInput) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelGroupInput) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *LabelGroupInput) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *LabelGroupInput) SetType(v string) {
	o.Type = &v
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *LabelGroupInput) GetOptional() bool {
	if o == nil || IsNil(o.Optional) {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelGroupInput) GetOptionalOk() (*bool, bool) {
	if o == nil || IsNil(o.Optional) {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *LabelGroupInput) HasOptional() bool {
	if o != nil && !IsNil(o.Optional) {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the Optional field.
func (o *LabelGroupInput) SetOptional(v bool) {
	o.Optional = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *LabelGroupInput) GetTag() bool {
	if o == nil || IsNil(o.Tag) {
		var ret bool
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelGroupInput) GetTagOk() (*bool, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *LabelGroupInput) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given bool and assigns it to the Tag field.
func (o *LabelGroupInput) SetTag(v bool) {
	o.Tag = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *LabelGroupInput) GetValues() []LabelValue {
	if o == nil || IsNil(o.Values) {
		var ret []LabelValue
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelGroupInput) GetValuesOk() ([]LabelValue, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *LabelGroupInput) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []LabelValue and assigns it to the Values field.
func (o *LabelGroupInput) SetValues(v []LabelValue) {
	o.Values = v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *LabelGroupInput) GetFields() map[string]MapFieldInput {
	if o == nil || IsNil(o.Fields) {
		var ret map[string]MapFieldInput
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelGroupInput) GetFieldsOk() (map[string]MapFieldInput, bool) {
	if o == nil || IsNil(o.Fields) {
		return map[string]MapFieldInput{}, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *LabelGroupInput) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given map[string]MapFieldInput and assigns it to the Fields field.
func (o *LabelGroupInput) SetFields(v map[string]MapFieldInput) {
	o.Fields = v
}

func (o LabelGroupInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelGroupInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Optional) {
		toSerialize["optional"] = o.Optional
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	return toSerialize, nil
}

func (o *LabelGroupInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLabelGroupInput := _LabelGroupInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLabelGroupInput)

	if err != nil {
		return err
	}

	*o = LabelGroupInput(varLabelGroupInput)

	return err
}

type NullableLabelGroupInput struct {
	value *LabelGroupInput
	isSet bool
}

func (v NullableLabelGroupInput) Get() *LabelGroupInput {
	return v.value
}

func (v *NullableLabelGroupInput) Set(val *LabelGroupInput) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelGroupInput) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelGroupInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelGroupInput(val *LabelGroupInput) *NullableLabelGroupInput {
	return &NullableLabelGroupInput{value: val, isSet: true}
}

func (v NullableLabelGroupInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelGroupInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


