/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the MentalModelRefreshOverrides type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentalModelRefreshOverrides{}

// MentalModelRefreshOverrides Per-run overrides for a mental model refresh.  Only meaningful for the dry run, which uses them to A/B a candidate configuration against the model's stored one without editing the model. Every field defaults to None, meaning \"use the model's stored setting\".
type MentalModelRefreshOverrides struct {
	Mode NullableString `json:"mode,omitempty"`
	SourceQuery NullableString `json:"source_query,omitempty"`
	Tags []string `json:"tags,omitempty"`
	TagsMatch NullableString `json:"tags_match,omitempty"`
	TagGroups []MentalModelRefreshOverridesTagGroupsInner `json:"tag_groups,omitempty"`
	FactTypes []string `json:"fact_types,omitempty"`
	ExcludeMentalModels NullableBool `json:"exclude_mental_models,omitempty"`
	MaxTokens NullableInt32 `json:"max_tokens,omitempty"`
	IncludeChunks NullableBool `json:"include_chunks,omitempty"`
	RecallMaxTokens NullableInt32 `json:"recall_max_tokens,omitempty"`
	RecallChunksMaxTokens NullableInt32 `json:"recall_chunks_max_tokens,omitempty"`
}

// NewMentalModelRefreshOverrides instantiates a new MentalModelRefreshOverrides object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentalModelRefreshOverrides() *MentalModelRefreshOverrides {
	this := MentalModelRefreshOverrides{}
	return &this
}

// NewMentalModelRefreshOverridesWithDefaults instantiates a new MentalModelRefreshOverrides object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentalModelRefreshOverridesWithDefaults() *MentalModelRefreshOverrides {
	this := MentalModelRefreshOverrides{}
	return &this
}

// GetMode returns the Mode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshOverrides) GetMode() string {
	if o == nil || IsNil(o.Mode.Get()) {
		var ret string
		return ret
	}
	return *o.Mode.Get()
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshOverrides) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mode.Get(), o.Mode.IsSet()
}

// HasMode returns a boolean if a field has been set.
func (o *MentalModelRefreshOverrides) HasMode() bool {
	if o != nil && o.Mode.IsSet() {
		return true
	}

	return false
}

// SetMode gets a reference to the given NullableString and assigns it to the Mode field.
func (o *MentalModelRefreshOverrides) SetMode(v string) {
	o.Mode.Set(&v)
}
// SetModeNil sets the value for Mode to be an explicit nil
func (o *MentalModelRefreshOverrides) SetModeNil() {
	o.Mode.Set(nil)
}

// UnsetMode ensures that no value is present for Mode, not even an explicit nil
func (o *MentalModelRefreshOverrides) UnsetMode() {
	o.Mode.Unset()
}

// GetSourceQuery returns the SourceQuery field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshOverrides) GetSourceQuery() string {
	if o == nil || IsNil(o.SourceQuery.Get()) {
		var ret string
		return ret
	}
	return *o.SourceQuery.Get()
}

// GetSourceQueryOk returns a tuple with the SourceQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshOverrides) GetSourceQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceQuery.Get(), o.SourceQuery.IsSet()
}

// HasSourceQuery returns a boolean if a field has been set.
func (o *MentalModelRefreshOverrides) HasSourceQuery() bool {
	if o != nil && o.SourceQuery.IsSet() {
		return true
	}

	return false
}

// SetSourceQuery gets a reference to the given NullableString and assigns it to the SourceQuery field.
func (o *MentalModelRefreshOverrides) SetSourceQuery(v string) {
	o.SourceQuery.Set(&v)
}
// SetSourceQueryNil sets the value for SourceQuery to be an explicit nil
func (o *MentalModelRefreshOverrides) SetSourceQueryNil() {
	o.SourceQuery.Set(nil)
}

// UnsetSourceQuery ensures that no value is present for SourceQuery, not even an explicit nil
func (o *MentalModelRefreshOverrides) UnsetSourceQuery() {
	o.SourceQuery.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshOverrides) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshOverrides) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *MentalModelRefreshOverrides) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *MentalModelRefreshOverrides) SetTags(v []string) {
	o.Tags = v
}

// GetTagsMatch returns the TagsMatch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshOverrides) GetTagsMatch() string {
	if o == nil || IsNil(o.TagsMatch.Get()) {
		var ret string
		return ret
	}
	return *o.TagsMatch.Get()
}

// GetTagsMatchOk returns a tuple with the TagsMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshOverrides) GetTagsMatchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TagsMatch.Get(), o.TagsMatch.IsSet()
}

// HasTagsMatch returns a boolean if a field has been set.
func (o *MentalModelRefreshOverrides) HasTagsMatch() bool {
	if o != nil && o.TagsMatch.IsSet() {
		return true
	}

	return false
}

// SetTagsMatch gets a reference to the given NullableString and assigns it to the TagsMatch field.
func (o *MentalModelRefreshOverrides) SetTagsMatch(v string) {
	o.TagsMatch.Set(&v)
}
// SetTagsMatchNil sets the value for TagsMatch to be an explicit nil
func (o *MentalModelRefreshOverrides) SetTagsMatchNil() {
	o.TagsMatch.Set(nil)
}

// UnsetTagsMatch ensures that no value is present for TagsMatch, not even an explicit nil
func (o *MentalModelRefreshOverrides) UnsetTagsMatch() {
	o.TagsMatch.Unset()
}

// GetTagGroups returns the TagGroups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshOverrides) GetTagGroups() []MentalModelRefreshOverridesTagGroupsInner {
	if o == nil {
		var ret []MentalModelRefreshOverridesTagGroupsInner
		return ret
	}
	return o.TagGroups
}

// GetTagGroupsOk returns a tuple with the TagGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshOverrides) GetTagGroupsOk() ([]MentalModelRefreshOverridesTagGroupsInner, bool) {
	if o == nil || IsNil(o.TagGroups) {
		return nil, false
	}
	return o.TagGroups, true
}

// HasTagGroups returns a boolean if a field has been set.
func (o *MentalModelRefreshOverrides) HasTagGroups() bool {
	if o != nil && !IsNil(o.TagGroups) {
		return true
	}

	return false
}

// SetTagGroups gets a reference to the given []MentalModelRefreshOverridesTagGroupsInner and assigns it to the TagGroups field.
func (o *MentalModelRefreshOverrides) SetTagGroups(v []MentalModelRefreshOverridesTagGroupsInner) {
	o.TagGroups = v
}

// GetFactTypes returns the FactTypes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshOverrides) GetFactTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.FactTypes
}

// GetFactTypesOk returns a tuple with the FactTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshOverrides) GetFactTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.FactTypes) {
		return nil, false
	}
	return o.FactTypes, true
}

// HasFactTypes returns a boolean if a field has been set.
func (o *MentalModelRefreshOverrides) HasFactTypes() bool {
	if o != nil && !IsNil(o.FactTypes) {
		return true
	}

	return false
}

// SetFactTypes gets a reference to the given []string and assigns it to the FactTypes field.
func (o *MentalModelRefreshOverrides) SetFactTypes(v []string) {
	o.FactTypes = v
}

// GetExcludeMentalModels returns the ExcludeMentalModels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshOverrides) GetExcludeMentalModels() bool {
	if o == nil || IsNil(o.ExcludeMentalModels.Get()) {
		var ret bool
		return ret
	}
	return *o.ExcludeMentalModels.Get()
}

// GetExcludeMentalModelsOk returns a tuple with the ExcludeMentalModels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshOverrides) GetExcludeMentalModelsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExcludeMentalModels.Get(), o.ExcludeMentalModels.IsSet()
}

// HasExcludeMentalModels returns a boolean if a field has been set.
func (o *MentalModelRefreshOverrides) HasExcludeMentalModels() bool {
	if o != nil && o.ExcludeMentalModels.IsSet() {
		return true
	}

	return false
}

// SetExcludeMentalModels gets a reference to the given NullableBool and assigns it to the ExcludeMentalModels field.
func (o *MentalModelRefreshOverrides) SetExcludeMentalModels(v bool) {
	o.ExcludeMentalModels.Set(&v)
}
// SetExcludeMentalModelsNil sets the value for ExcludeMentalModels to be an explicit nil
func (o *MentalModelRefreshOverrides) SetExcludeMentalModelsNil() {
	o.ExcludeMentalModels.Set(nil)
}

// UnsetExcludeMentalModels ensures that no value is present for ExcludeMentalModels, not even an explicit nil
func (o *MentalModelRefreshOverrides) UnsetExcludeMentalModels() {
	o.ExcludeMentalModels.Unset()
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshOverrides) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxTokens.Get()
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshOverrides) GetMaxTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxTokens.Get(), o.MaxTokens.IsSet()
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *MentalModelRefreshOverrides) HasMaxTokens() bool {
	if o != nil && o.MaxTokens.IsSet() {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given NullableInt32 and assigns it to the MaxTokens field.
func (o *MentalModelRefreshOverrides) SetMaxTokens(v int32) {
	o.MaxTokens.Set(&v)
}
// SetMaxTokensNil sets the value for MaxTokens to be an explicit nil
func (o *MentalModelRefreshOverrides) SetMaxTokensNil() {
	o.MaxTokens.Set(nil)
}

// UnsetMaxTokens ensures that no value is present for MaxTokens, not even an explicit nil
func (o *MentalModelRefreshOverrides) UnsetMaxTokens() {
	o.MaxTokens.Unset()
}

// GetIncludeChunks returns the IncludeChunks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshOverrides) GetIncludeChunks() bool {
	if o == nil || IsNil(o.IncludeChunks.Get()) {
		var ret bool
		return ret
	}
	return *o.IncludeChunks.Get()
}

// GetIncludeChunksOk returns a tuple with the IncludeChunks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshOverrides) GetIncludeChunksOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IncludeChunks.Get(), o.IncludeChunks.IsSet()
}

// HasIncludeChunks returns a boolean if a field has been set.
func (o *MentalModelRefreshOverrides) HasIncludeChunks() bool {
	if o != nil && o.IncludeChunks.IsSet() {
		return true
	}

	return false
}

// SetIncludeChunks gets a reference to the given NullableBool and assigns it to the IncludeChunks field.
func (o *MentalModelRefreshOverrides) SetIncludeChunks(v bool) {
	o.IncludeChunks.Set(&v)
}
// SetIncludeChunksNil sets the value for IncludeChunks to be an explicit nil
func (o *MentalModelRefreshOverrides) SetIncludeChunksNil() {
	o.IncludeChunks.Set(nil)
}

// UnsetIncludeChunks ensures that no value is present for IncludeChunks, not even an explicit nil
func (o *MentalModelRefreshOverrides) UnsetIncludeChunks() {
	o.IncludeChunks.Unset()
}

// GetRecallMaxTokens returns the RecallMaxTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshOverrides) GetRecallMaxTokens() int32 {
	if o == nil || IsNil(o.RecallMaxTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.RecallMaxTokens.Get()
}

// GetRecallMaxTokensOk returns a tuple with the RecallMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshOverrides) GetRecallMaxTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecallMaxTokens.Get(), o.RecallMaxTokens.IsSet()
}

// HasRecallMaxTokens returns a boolean if a field has been set.
func (o *MentalModelRefreshOverrides) HasRecallMaxTokens() bool {
	if o != nil && o.RecallMaxTokens.IsSet() {
		return true
	}

	return false
}

// SetRecallMaxTokens gets a reference to the given NullableInt32 and assigns it to the RecallMaxTokens field.
func (o *MentalModelRefreshOverrides) SetRecallMaxTokens(v int32) {
	o.RecallMaxTokens.Set(&v)
}
// SetRecallMaxTokensNil sets the value for RecallMaxTokens to be an explicit nil
func (o *MentalModelRefreshOverrides) SetRecallMaxTokensNil() {
	o.RecallMaxTokens.Set(nil)
}

// UnsetRecallMaxTokens ensures that no value is present for RecallMaxTokens, not even an explicit nil
func (o *MentalModelRefreshOverrides) UnsetRecallMaxTokens() {
	o.RecallMaxTokens.Unset()
}

// GetRecallChunksMaxTokens returns the RecallChunksMaxTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshOverrides) GetRecallChunksMaxTokens() int32 {
	if o == nil || IsNil(o.RecallChunksMaxTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.RecallChunksMaxTokens.Get()
}

// GetRecallChunksMaxTokensOk returns a tuple with the RecallChunksMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshOverrides) GetRecallChunksMaxTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecallChunksMaxTokens.Get(), o.RecallChunksMaxTokens.IsSet()
}

// HasRecallChunksMaxTokens returns a boolean if a field has been set.
func (o *MentalModelRefreshOverrides) HasRecallChunksMaxTokens() bool {
	if o != nil && o.RecallChunksMaxTokens.IsSet() {
		return true
	}

	return false
}

// SetRecallChunksMaxTokens gets a reference to the given NullableInt32 and assigns it to the RecallChunksMaxTokens field.
func (o *MentalModelRefreshOverrides) SetRecallChunksMaxTokens(v int32) {
	o.RecallChunksMaxTokens.Set(&v)
}
// SetRecallChunksMaxTokensNil sets the value for RecallChunksMaxTokens to be an explicit nil
func (o *MentalModelRefreshOverrides) SetRecallChunksMaxTokensNil() {
	o.RecallChunksMaxTokens.Set(nil)
}

// UnsetRecallChunksMaxTokens ensures that no value is present for RecallChunksMaxTokens, not even an explicit nil
func (o *MentalModelRefreshOverrides) UnsetRecallChunksMaxTokens() {
	o.RecallChunksMaxTokens.Unset()
}

func (o MentalModelRefreshOverrides) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentalModelRefreshOverrides) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Mode.IsSet() {
		toSerialize["mode"] = o.Mode.Get()
	}
	if o.SourceQuery.IsSet() {
		toSerialize["source_query"] = o.SourceQuery.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.TagsMatch.IsSet() {
		toSerialize["tags_match"] = o.TagsMatch.Get()
	}
	if o.TagGroups != nil {
		toSerialize["tag_groups"] = o.TagGroups
	}
	if o.FactTypes != nil {
		toSerialize["fact_types"] = o.FactTypes
	}
	if o.ExcludeMentalModels.IsSet() {
		toSerialize["exclude_mental_models"] = o.ExcludeMentalModels.Get()
	}
	if o.MaxTokens.IsSet() {
		toSerialize["max_tokens"] = o.MaxTokens.Get()
	}
	if o.IncludeChunks.IsSet() {
		toSerialize["include_chunks"] = o.IncludeChunks.Get()
	}
	if o.RecallMaxTokens.IsSet() {
		toSerialize["recall_max_tokens"] = o.RecallMaxTokens.Get()
	}
	if o.RecallChunksMaxTokens.IsSet() {
		toSerialize["recall_chunks_max_tokens"] = o.RecallChunksMaxTokens.Get()
	}
	return toSerialize, nil
}

type NullableMentalModelRefreshOverrides struct {
	value *MentalModelRefreshOverrides
	isSet bool
}

func (v NullableMentalModelRefreshOverrides) Get() *MentalModelRefreshOverrides {
	return v.value
}

func (v *NullableMentalModelRefreshOverrides) Set(val *MentalModelRefreshOverrides) {
	v.value = val
	v.isSet = true
}

func (v NullableMentalModelRefreshOverrides) IsSet() bool {
	return v.isSet
}

func (v *NullableMentalModelRefreshOverrides) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentalModelRefreshOverrides(val *MentalModelRefreshOverrides) *NullableMentalModelRefreshOverrides {
	return &NullableMentalModelRefreshOverrides{value: val, isSet: true}
}

func (v NullableMentalModelRefreshOverrides) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentalModelRefreshOverrides) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


