/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DirectiveListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectiveListResponse{}

// DirectiveListResponse Response model for listing directives.
type DirectiveListResponse struct {
	Items []DirectiveResponse `json:"items"`
	// Total number of directives matching the filter (not just this page)
	Total int32 `json:"total"`
	// Page size that was applied
	Limit int32 `json:"limit"`
	// Offset that was applied
	Offset int32 `json:"offset"`
}

type _DirectiveListResponse DirectiveListResponse

// NewDirectiveListResponse instantiates a new DirectiveListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectiveListResponse(items []DirectiveResponse, total int32, limit int32, offset int32) *DirectiveListResponse {
	this := DirectiveListResponse{}
	this.Items = items
	this.Total = total
	this.Limit = limit
	this.Offset = offset
	return &this
}

// NewDirectiveListResponseWithDefaults instantiates a new DirectiveListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectiveListResponseWithDefaults() *DirectiveListResponse {
	this := DirectiveListResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *DirectiveListResponse) GetItems() []DirectiveResponse {
	if o == nil {
		var ret []DirectiveResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *DirectiveListResponse) GetItemsOk() ([]DirectiveResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *DirectiveListResponse) SetItems(v []DirectiveResponse) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *DirectiveListResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *DirectiveListResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *DirectiveListResponse) SetTotal(v int32) {
	o.Total = v
}

// GetLimit returns the Limit field value
func (o *DirectiveListResponse) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *DirectiveListResponse) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *DirectiveListResponse) SetLimit(v int32) {
	o.Limit = v
}

// GetOffset returns the Offset field value
func (o *DirectiveListResponse) GetOffset() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value
// and a boolean to check if the value has been set.
func (o *DirectiveListResponse) GetOffsetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offset, true
}

// SetOffset sets field value
func (o *DirectiveListResponse) SetOffset(v int32) {
	o.Offset = v
}

func (o DirectiveListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectiveListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total
	toSerialize["limit"] = o.Limit
	toSerialize["offset"] = o.Offset
	return toSerialize, nil
}

func (o *DirectiveListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"total",
		"limit",
		"offset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectiveListResponse := _DirectiveListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDirectiveListResponse)

	if err != nil {
		return err
	}

	*o = DirectiveListResponse(varDirectiveListResponse)

	return err
}

type NullableDirectiveListResponse struct {
	value *DirectiveListResponse
	isSet bool
}

func (v NullableDirectiveListResponse) Get() *DirectiveListResponse {
	return v.value
}

func (v *NullableDirectiveListResponse) Set(val *DirectiveListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectiveListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectiveListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectiveListResponse(val *DirectiveListResponse) *NullableDirectiveListResponse {
	return &NullableDirectiveListResponse{value: val, isSet: true}
}

func (v NullableDirectiveListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectiveListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


