/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RecallScores type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecallScores{}

// RecallScores Per-result recall scores from different stages of the pipeline.  ``final`` is the value results are ranked by. The others are diagnostic and can be filtered on via the recall ``min_scores`` request parameter. ``semantic`` and ``keyword`` are the raw per-strategy retrieval scores (``None`` when that strategy did not surface this result); ``reranker`` is the cross-encoder's normalized relevance.
type RecallScores struct {
	// Final ranking score (combined reranker + recency/temporal/proof boosts)
	Final float32 `json:"final"`
	Reranker NullableFloat32 `json:"reranker,omitempty"`
	Semantic NullableFloat32 `json:"semantic,omitempty"`
	Keyword NullableFloat32 `json:"keyword,omitempty"`
}

type _RecallScores RecallScores

// NewRecallScores instantiates a new RecallScores object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecallScores(final float32) *RecallScores {
	this := RecallScores{}
	this.Final = final
	return &this
}

// NewRecallScoresWithDefaults instantiates a new RecallScores object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecallScoresWithDefaults() *RecallScores {
	this := RecallScores{}
	return &this
}

// GetFinal returns the Final field value
func (o *RecallScores) GetFinal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Final
}

// GetFinalOk returns a tuple with the Final field value
// and a boolean to check if the value has been set.
func (o *RecallScores) GetFinalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Final, true
}

// SetFinal sets field value
func (o *RecallScores) SetFinal(v float32) {
	o.Final = v
}

// GetReranker returns the Reranker field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecallScores) GetReranker() float32 {
	if o == nil || IsNil(o.Reranker.Get()) {
		var ret float32
		return ret
	}
	return *o.Reranker.Get()
}

// GetRerankerOk returns a tuple with the Reranker field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecallScores) GetRerankerOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reranker.Get(), o.Reranker.IsSet()
}

// HasReranker returns a boolean if a field has been set.
func (o *RecallScores) HasReranker() bool {
	if o != nil && o.Reranker.IsSet() {
		return true
	}

	return false
}

// SetReranker gets a reference to the given NullableFloat32 and assigns it to the Reranker field.
func (o *RecallScores) SetReranker(v float32) {
	o.Reranker.Set(&v)
}
// SetRerankerNil sets the value for Reranker to be an explicit nil
func (o *RecallScores) SetRerankerNil() {
	o.Reranker.Set(nil)
}

// UnsetReranker ensures that no value is present for Reranker, not even an explicit nil
func (o *RecallScores) UnsetReranker() {
	o.Reranker.Unset()
}

// GetSemantic returns the Semantic field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecallScores) GetSemantic() float32 {
	if o == nil || IsNil(o.Semantic.Get()) {
		var ret float32
		return ret
	}
	return *o.Semantic.Get()
}

// GetSemanticOk returns a tuple with the Semantic field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecallScores) GetSemanticOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Semantic.Get(), o.Semantic.IsSet()
}

// HasSemantic returns a boolean if a field has been set.
func (o *RecallScores) HasSemantic() bool {
	if o != nil && o.Semantic.IsSet() {
		return true
	}

	return false
}

// SetSemantic gets a reference to the given NullableFloat32 and assigns it to the Semantic field.
func (o *RecallScores) SetSemantic(v float32) {
	o.Semantic.Set(&v)
}
// SetSemanticNil sets the value for Semantic to be an explicit nil
func (o *RecallScores) SetSemanticNil() {
	o.Semantic.Set(nil)
}

// UnsetSemantic ensures that no value is present for Semantic, not even an explicit nil
func (o *RecallScores) UnsetSemantic() {
	o.Semantic.Unset()
}

// GetKeyword returns the Keyword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RecallScores) GetKeyword() float32 {
	if o == nil || IsNil(o.Keyword.Get()) {
		var ret float32
		return ret
	}
	return *o.Keyword.Get()
}

// GetKeywordOk returns a tuple with the Keyword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RecallScores) GetKeywordOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keyword.Get(), o.Keyword.IsSet()
}

// HasKeyword returns a boolean if a field has been set.
func (o *RecallScores) HasKeyword() bool {
	if o != nil && o.Keyword.IsSet() {
		return true
	}

	return false
}

// SetKeyword gets a reference to the given NullableFloat32 and assigns it to the Keyword field.
func (o *RecallScores) SetKeyword(v float32) {
	o.Keyword.Set(&v)
}
// SetKeywordNil sets the value for Keyword to be an explicit nil
func (o *RecallScores) SetKeywordNil() {
	o.Keyword.Set(nil)
}

// UnsetKeyword ensures that no value is present for Keyword, not even an explicit nil
func (o *RecallScores) UnsetKeyword() {
	o.Keyword.Unset()
}

func (o RecallScores) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecallScores) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["final"] = o.Final
	if o.Reranker.IsSet() {
		toSerialize["reranker"] = o.Reranker.Get()
	}
	if o.Semantic.IsSet() {
		toSerialize["semantic"] = o.Semantic.Get()
	}
	if o.Keyword.IsSet() {
		toSerialize["keyword"] = o.Keyword.Get()
	}
	return toSerialize, nil
}

func (o *RecallScores) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"final",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRecallScores := _RecallScores{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRecallScores)

	if err != nil {
		return err
	}

	*o = RecallScores(varRecallScores)

	return err
}

type NullableRecallScores struct {
	value *RecallScores
	isSet bool
}

func (v NullableRecallScores) Get() *RecallScores {
	return v.value
}

func (v *NullableRecallScores) Set(val *RecallScores) {
	v.value = val
	v.isSet = true
}

func (v NullableRecallScores) IsSet() bool {
	return v.isSet
}

func (v *NullableRecallScores) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecallScores(val *RecallScores) *NullableRecallScores {
	return &NullableRecallScores{value: val, isSet: true}
}

func (v NullableRecallScores) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecallScores) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


