/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MentalModelRefreshScope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentalModelRefreshScope{}

// MentalModelRefreshScope The memory scope a refresh actually resolved to.  A model's stored ``tags`` are not what filters memories — ``tags_match`` defaults to ``all_strict`` when tags are present, and ``tag_groups`` override flat tags entirely. This reports the resolved result.
type MentalModelRefreshScope struct {
	Tags []string `json:"tags,omitempty"`
	// Resolved tag match mode.
	TagsMatch string `json:"tags_match"`
	TagGroups []MentalModelRefreshScopeTagGroupsInner `json:"tag_groups,omitempty"`
	FactTypes []string `json:"fact_types,omitempty"`
	// Whether other mental models were excluded from the reflect loop.
	ExcludeMentalModels bool `json:"exclude_mental_models"`
	// Mental models excluded by ID (always includes the model being refreshed).
	ExcludeMentalModelIds []string `json:"exclude_mental_model_ids,omitempty"`
}

type _MentalModelRefreshScope MentalModelRefreshScope

// NewMentalModelRefreshScope instantiates a new MentalModelRefreshScope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentalModelRefreshScope(tagsMatch string, excludeMentalModels bool) *MentalModelRefreshScope {
	this := MentalModelRefreshScope{}
	this.TagsMatch = tagsMatch
	this.ExcludeMentalModels = excludeMentalModels
	return &this
}

// NewMentalModelRefreshScopeWithDefaults instantiates a new MentalModelRefreshScope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentalModelRefreshScopeWithDefaults() *MentalModelRefreshScope {
	this := MentalModelRefreshScope{}
	return &this
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshScope) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshScope) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *MentalModelRefreshScope) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *MentalModelRefreshScope) SetTags(v []string) {
	o.Tags = v
}

// GetTagsMatch returns the TagsMatch field value
func (o *MentalModelRefreshScope) GetTagsMatch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TagsMatch
}

// GetTagsMatchOk returns a tuple with the TagsMatch field value
// and a boolean to check if the value has been set.
func (o *MentalModelRefreshScope) GetTagsMatchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TagsMatch, true
}

// SetTagsMatch sets field value
func (o *MentalModelRefreshScope) SetTagsMatch(v string) {
	o.TagsMatch = v
}

// GetTagGroups returns the TagGroups field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshScope) GetTagGroups() []MentalModelRefreshScopeTagGroupsInner {
	if o == nil {
		var ret []MentalModelRefreshScopeTagGroupsInner
		return ret
	}
	return o.TagGroups
}

// GetTagGroupsOk returns a tuple with the TagGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshScope) GetTagGroupsOk() ([]MentalModelRefreshScopeTagGroupsInner, bool) {
	if o == nil || IsNil(o.TagGroups) {
		return nil, false
	}
	return o.TagGroups, true
}

// HasTagGroups returns a boolean if a field has been set.
func (o *MentalModelRefreshScope) HasTagGroups() bool {
	if o != nil && !IsNil(o.TagGroups) {
		return true
	}

	return false
}

// SetTagGroups gets a reference to the given []MentalModelRefreshScopeTagGroupsInner and assigns it to the TagGroups field.
func (o *MentalModelRefreshScope) SetTagGroups(v []MentalModelRefreshScopeTagGroupsInner) {
	o.TagGroups = v
}

// GetFactTypes returns the FactTypes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshScope) GetFactTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.FactTypes
}

// GetFactTypesOk returns a tuple with the FactTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshScope) GetFactTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.FactTypes) {
		return nil, false
	}
	return o.FactTypes, true
}

// HasFactTypes returns a boolean if a field has been set.
func (o *MentalModelRefreshScope) HasFactTypes() bool {
	if o != nil && !IsNil(o.FactTypes) {
		return true
	}

	return false
}

// SetFactTypes gets a reference to the given []string and assigns it to the FactTypes field.
func (o *MentalModelRefreshScope) SetFactTypes(v []string) {
	o.FactTypes = v
}

// GetExcludeMentalModels returns the ExcludeMentalModels field value
func (o *MentalModelRefreshScope) GetExcludeMentalModels() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ExcludeMentalModels
}

// GetExcludeMentalModelsOk returns a tuple with the ExcludeMentalModels field value
// and a boolean to check if the value has been set.
func (o *MentalModelRefreshScope) GetExcludeMentalModelsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExcludeMentalModels, true
}

// SetExcludeMentalModels sets field value
func (o *MentalModelRefreshScope) SetExcludeMentalModels(v bool) {
	o.ExcludeMentalModels = v
}

// GetExcludeMentalModelIds returns the ExcludeMentalModelIds field value if set, zero value otherwise.
func (o *MentalModelRefreshScope) GetExcludeMentalModelIds() []string {
	if o == nil || IsNil(o.ExcludeMentalModelIds) {
		var ret []string
		return ret
	}
	return o.ExcludeMentalModelIds
}

// GetExcludeMentalModelIdsOk returns a tuple with the ExcludeMentalModelIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelRefreshScope) GetExcludeMentalModelIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeMentalModelIds) {
		return nil, false
	}
	return o.ExcludeMentalModelIds, true
}

// HasExcludeMentalModelIds returns a boolean if a field has been set.
func (o *MentalModelRefreshScope) HasExcludeMentalModelIds() bool {
	if o != nil && !IsNil(o.ExcludeMentalModelIds) {
		return true
	}

	return false
}

// SetExcludeMentalModelIds gets a reference to the given []string and assigns it to the ExcludeMentalModelIds field.
func (o *MentalModelRefreshScope) SetExcludeMentalModelIds(v []string) {
	o.ExcludeMentalModelIds = v
}

func (o MentalModelRefreshScope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentalModelRefreshScope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["tags_match"] = o.TagsMatch
	if o.TagGroups != nil {
		toSerialize["tag_groups"] = o.TagGroups
	}
	if o.FactTypes != nil {
		toSerialize["fact_types"] = o.FactTypes
	}
	toSerialize["exclude_mental_models"] = o.ExcludeMentalModels
	if !IsNil(o.ExcludeMentalModelIds) {
		toSerialize["exclude_mental_model_ids"] = o.ExcludeMentalModelIds
	}
	return toSerialize, nil
}

func (o *MentalModelRefreshScope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tags_match",
		"exclude_mental_models",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMentalModelRefreshScope := _MentalModelRefreshScope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMentalModelRefreshScope)

	if err != nil {
		return err
	}

	*o = MentalModelRefreshScope(varMentalModelRefreshScope)

	return err
}

type NullableMentalModelRefreshScope struct {
	value *MentalModelRefreshScope
	isSet bool
}

func (v NullableMentalModelRefreshScope) Get() *MentalModelRefreshScope {
	return v.value
}

func (v *NullableMentalModelRefreshScope) Set(val *MentalModelRefreshScope) {
	v.value = val
	v.isSet = true
}

func (v NullableMentalModelRefreshScope) IsSet() bool {
	return v.isSet
}

func (v *NullableMentalModelRefreshScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentalModelRefreshScope(val *MentalModelRefreshScope) *NullableMentalModelRefreshScope {
	return &NullableMentalModelRefreshScope{value: val, isSet: true}
}

func (v NullableMentalModelRefreshScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentalModelRefreshScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


