/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the MentalModelFactCounts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentalModelFactCounts{}

// MentalModelFactCounts Facts the refresh saw, keyed by fact type.  ``retrieved`` and ``used`` diverging is the single most common cause of a disappointing refresh: recall found plenty, but the reflect agent declared none of it relevant to the topic, so none of it reached the document.
type MentalModelFactCounts struct {
	// Facts the reflect agent's tool calls returned, by fact type.
	Retrieved map[string]int32 `json:"retrieved,omitempty"`
	// Facts the agent declared it actually based the answer on, by fact type.
	Used map[string]int32 `json:"used,omitempty"`
}

// NewMentalModelFactCounts instantiates a new MentalModelFactCounts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentalModelFactCounts() *MentalModelFactCounts {
	this := MentalModelFactCounts{}
	return &this
}

// NewMentalModelFactCountsWithDefaults instantiates a new MentalModelFactCounts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentalModelFactCountsWithDefaults() *MentalModelFactCounts {
	this := MentalModelFactCounts{}
	return &this
}

// GetRetrieved returns the Retrieved field value if set, zero value otherwise.
func (o *MentalModelFactCounts) GetRetrieved() map[string]int32 {
	if o == nil || IsNil(o.Retrieved) {
		var ret map[string]int32
		return ret
	}
	return o.Retrieved
}

// GetRetrievedOk returns a tuple with the Retrieved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelFactCounts) GetRetrievedOk() (map[string]int32, bool) {
	if o == nil || IsNil(o.Retrieved) {
		return map[string]int32{}, false
	}
	return o.Retrieved, true
}

// HasRetrieved returns a boolean if a field has been set.
func (o *MentalModelFactCounts) HasRetrieved() bool {
	if o != nil && !IsNil(o.Retrieved) {
		return true
	}

	return false
}

// SetRetrieved gets a reference to the given map[string]int32 and assigns it to the Retrieved field.
func (o *MentalModelFactCounts) SetRetrieved(v map[string]int32) {
	o.Retrieved = v
}

// GetUsed returns the Used field value if set, zero value otherwise.
func (o *MentalModelFactCounts) GetUsed() map[string]int32 {
	if o == nil || IsNil(o.Used) {
		var ret map[string]int32
		return ret
	}
	return o.Used
}

// GetUsedOk returns a tuple with the Used field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelFactCounts) GetUsedOk() (map[string]int32, bool) {
	if o == nil || IsNil(o.Used) {
		return map[string]int32{}, false
	}
	return o.Used, true
}

// HasUsed returns a boolean if a field has been set.
func (o *MentalModelFactCounts) HasUsed() bool {
	if o != nil && !IsNil(o.Used) {
		return true
	}

	return false
}

// SetUsed gets a reference to the given map[string]int32 and assigns it to the Used field.
func (o *MentalModelFactCounts) SetUsed(v map[string]int32) {
	o.Used = v
}

func (o MentalModelFactCounts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentalModelFactCounts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Retrieved) {
		toSerialize["retrieved"] = o.Retrieved
	}
	if !IsNil(o.Used) {
		toSerialize["used"] = o.Used
	}
	return toSerialize, nil
}

type NullableMentalModelFactCounts struct {
	value *MentalModelFactCounts
	isSet bool
}

func (v NullableMentalModelFactCounts) Get() *MentalModelFactCounts {
	return v.value
}

func (v *NullableMentalModelFactCounts) Set(val *MentalModelFactCounts) {
	v.value = val
	v.isSet = true
}

func (v NullableMentalModelFactCounts) IsSet() bool {
	return v.isSet
}

func (v *NullableMentalModelFactCounts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentalModelFactCounts(val *MentalModelFactCounts) *NullableMentalModelFactCounts {
	return &NullableMentalModelFactCounts{value: val, isSet: true}
}

func (v NullableMentalModelFactCounts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentalModelFactCounts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


