/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the MapFieldOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MapFieldOutput{}

// MapFieldOutput A field within a map-type entity label group. Supports recursion via type='map'.
type MapFieldOutput struct {
	Type *string `json:"type,omitempty"`
	Description *string `json:"description,omitempty"`
	Values []LabelValue `json:"values,omitempty"`
	Fields map[string]MapFieldOutput `json:"fields,omitempty"`
}

// NewMapFieldOutput instantiates a new MapFieldOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMapFieldOutput() *MapFieldOutput {
	this := MapFieldOutput{}
	var type_ string = "text"
	this.Type = &type_
	var description string = ""
	this.Description = &description
	return &this
}

// NewMapFieldOutputWithDefaults instantiates a new MapFieldOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMapFieldOutputWithDefaults() *MapFieldOutput {
	this := MapFieldOutput{}
	var type_ string = "text"
	this.Type = &type_
	var description string = ""
	this.Description = &description
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *MapFieldOutput) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapFieldOutput) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *MapFieldOutput) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *MapFieldOutput) SetType(v string) {
	o.Type = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MapFieldOutput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapFieldOutput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MapFieldOutput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MapFieldOutput) SetDescription(v string) {
	o.Description = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *MapFieldOutput) GetValues() []LabelValue {
	if o == nil || IsNil(o.Values) {
		var ret []LabelValue
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapFieldOutput) GetValuesOk() ([]LabelValue, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *MapFieldOutput) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []LabelValue and assigns it to the Values field.
func (o *MapFieldOutput) SetValues(v []LabelValue) {
	o.Values = v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *MapFieldOutput) GetFields() map[string]MapFieldOutput {
	if o == nil || IsNil(o.Fields) {
		var ret map[string]MapFieldOutput
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapFieldOutput) GetFieldsOk() (map[string]MapFieldOutput, bool) {
	if o == nil || IsNil(o.Fields) {
		return map[string]MapFieldOutput{}, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *MapFieldOutput) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given map[string]MapFieldOutput and assigns it to the Fields field.
func (o *MapFieldOutput) SetFields(v map[string]MapFieldOutput) {
	o.Fields = v
}

func (o MapFieldOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MapFieldOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	return toSerialize, nil
}

type NullableMapFieldOutput struct {
	value *MapFieldOutput
	isSet bool
}

func (v NullableMapFieldOutput) Get() *MapFieldOutput {
	return v.value
}

func (v *NullableMapFieldOutput) Set(val *MapFieldOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableMapFieldOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableMapFieldOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMapFieldOutput(val *MapFieldOutput) *NullableMapFieldOutput {
	return &NullableMapFieldOutput{value: val, isSet: true}
}

func (v NullableMapFieldOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMapFieldOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


