/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LabelValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelValue{}

// LabelValue A single allowed value for a label group.
type LabelValue struct {
	Value string `json:"value"`
	Description *string `json:"description,omitempty"`
}

type _LabelValue LabelValue

// NewLabelValue instantiates a new LabelValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelValue(value string) *LabelValue {
	this := LabelValue{}
	this.Value = value
	var description string = ""
	this.Description = &description
	return &this
}

// NewLabelValueWithDefaults instantiates a new LabelValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelValueWithDefaults() *LabelValue {
	this := LabelValue{}
	var description string = ""
	this.Description = &description
	return &this
}

// GetValue returns the Value field value
func (o *LabelValue) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *LabelValue) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *LabelValue) SetValue(v string) {
	o.Value = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *LabelValue) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelValue) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *LabelValue) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *LabelValue) SetDescription(v string) {
	o.Description = &v
}

func (o LabelValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

func (o *LabelValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLabelValue := _LabelValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLabelValue)

	if err != nil {
		return err
	}

	*o = LabelValue(varLabelValue)

	return err
}

type NullableLabelValue struct {
	value *LabelValue
	isSet bool
}

func (v NullableLabelValue) Get() *LabelValue {
	return v.value
}

func (v *NullableLabelValue) Set(val *LabelValue) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelValue) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelValue(val *LabelValue) *NullableLabelValue {
	return &NullableLabelValue{value: val, isSet: true}
}

func (v NullableLabelValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


