/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MentalModelTraceToolCall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentalModelTraceToolCall{}

// MentalModelTraceToolCall One reflect tool call made during a refresh.  ``output`` is carried only by the dry run, which persists nothing. The trace stored on the model row keeps ``result_count`` instead: it is re-read on every fetch, so embedding full recall payloads there would bloat the row without bound. Raw prompts and responses are available separately via LLM request tracing.
type MentalModelTraceToolCall struct {
	// Tool name: recall, search_observations, get_mental_model, expand, …
	Tool string `json:"tool"`
	Reason NullableString `json:"reason,omitempty"`
	// Tool input parameters.
	Input map[string]interface{} `json:"input,omitempty"`
	Output map[string]interface{} `json:"output,omitempty"`
	UpdatedAt NullableTime `json:"updated_at,omitempty"`
	ResultCount NullableInt32 `json:"result_count,omitempty"`
	// Execution time in milliseconds.
	DurationMs int32 `json:"duration_ms"`
	// Agent loop iteration (1-based) this call belongs to.
	Iteration *int32 `json:"iteration,omitempty"`
}

type _MentalModelTraceToolCall MentalModelTraceToolCall

// NewMentalModelTraceToolCall instantiates a new MentalModelTraceToolCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentalModelTraceToolCall(tool string, durationMs int32) *MentalModelTraceToolCall {
	this := MentalModelTraceToolCall{}
	this.Tool = tool
	this.DurationMs = durationMs
	var iteration int32 = 0
	this.Iteration = &iteration
	return &this
}

// NewMentalModelTraceToolCallWithDefaults instantiates a new MentalModelTraceToolCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentalModelTraceToolCallWithDefaults() *MentalModelTraceToolCall {
	this := MentalModelTraceToolCall{}
	var iteration int32 = 0
	this.Iteration = &iteration
	return &this
}

// GetTool returns the Tool field value
func (o *MentalModelTraceToolCall) GetTool() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tool
}

// GetToolOk returns a tuple with the Tool field value
// and a boolean to check if the value has been set.
func (o *MentalModelTraceToolCall) GetToolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tool, true
}

// SetTool sets field value
func (o *MentalModelTraceToolCall) SetTool(v string) {
	o.Tool = v
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTraceToolCall) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTraceToolCall) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *MentalModelTraceToolCall) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *MentalModelTraceToolCall) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *MentalModelTraceToolCall) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *MentalModelTraceToolCall) UnsetReason() {
	o.Reason.Unset()
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *MentalModelTraceToolCall) GetInput() map[string]interface{} {
	if o == nil || IsNil(o.Input) {
		var ret map[string]interface{}
		return ret
	}
	return o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelTraceToolCall) GetInputOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Input) {
		return map[string]interface{}{}, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *MentalModelTraceToolCall) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given map[string]interface{} and assigns it to the Input field.
func (o *MentalModelTraceToolCall) SetInput(v map[string]interface{}) {
	o.Input = v
}

// GetOutput returns the Output field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTraceToolCall) GetOutput() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Output
}

// GetOutputOk returns a tuple with the Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTraceToolCall) GetOutputOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Output) {
		return map[string]interface{}{}, false
	}
	return o.Output, true
}

// HasOutput returns a boolean if a field has been set.
func (o *MentalModelTraceToolCall) HasOutput() bool {
	if o != nil && !IsNil(o.Output) {
		return true
	}

	return false
}

// SetOutput gets a reference to the given map[string]interface{} and assigns it to the Output field.
func (o *MentalModelTraceToolCall) SetOutput(v map[string]interface{}) {
	o.Output = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTraceToolCall) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt.Get()
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTraceToolCall) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedAt.Get(), o.UpdatedAt.IsSet()
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *MentalModelTraceToolCall) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt.IsSet() {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given NullableTime and assigns it to the UpdatedAt field.
func (o *MentalModelTraceToolCall) SetUpdatedAt(v time.Time) {
	o.UpdatedAt.Set(&v)
}
// SetUpdatedAtNil sets the value for UpdatedAt to be an explicit nil
func (o *MentalModelTraceToolCall) SetUpdatedAtNil() {
	o.UpdatedAt.Set(nil)
}

// UnsetUpdatedAt ensures that no value is present for UpdatedAt, not even an explicit nil
func (o *MentalModelTraceToolCall) UnsetUpdatedAt() {
	o.UpdatedAt.Unset()
}

// GetResultCount returns the ResultCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelTraceToolCall) GetResultCount() int32 {
	if o == nil || IsNil(o.ResultCount.Get()) {
		var ret int32
		return ret
	}
	return *o.ResultCount.Get()
}

// GetResultCountOk returns a tuple with the ResultCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelTraceToolCall) GetResultCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultCount.Get(), o.ResultCount.IsSet()
}

// HasResultCount returns a boolean if a field has been set.
func (o *MentalModelTraceToolCall) HasResultCount() bool {
	if o != nil && o.ResultCount.IsSet() {
		return true
	}

	return false
}

// SetResultCount gets a reference to the given NullableInt32 and assigns it to the ResultCount field.
func (o *MentalModelTraceToolCall) SetResultCount(v int32) {
	o.ResultCount.Set(&v)
}
// SetResultCountNil sets the value for ResultCount to be an explicit nil
func (o *MentalModelTraceToolCall) SetResultCountNil() {
	o.ResultCount.Set(nil)
}

// UnsetResultCount ensures that no value is present for ResultCount, not even an explicit nil
func (o *MentalModelTraceToolCall) UnsetResultCount() {
	o.ResultCount.Unset()
}

// GetDurationMs returns the DurationMs field value
func (o *MentalModelTraceToolCall) GetDurationMs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value
// and a boolean to check if the value has been set.
func (o *MentalModelTraceToolCall) GetDurationMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationMs, true
}

// SetDurationMs sets field value
func (o *MentalModelTraceToolCall) SetDurationMs(v int32) {
	o.DurationMs = v
}

// GetIteration returns the Iteration field value if set, zero value otherwise.
func (o *MentalModelTraceToolCall) GetIteration() int32 {
	if o == nil || IsNil(o.Iteration) {
		var ret int32
		return ret
	}
	return *o.Iteration
}

// GetIterationOk returns a tuple with the Iteration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelTraceToolCall) GetIterationOk() (*int32, bool) {
	if o == nil || IsNil(o.Iteration) {
		return nil, false
	}
	return o.Iteration, true
}

// HasIteration returns a boolean if a field has been set.
func (o *MentalModelTraceToolCall) HasIteration() bool {
	if o != nil && !IsNil(o.Iteration) {
		return true
	}

	return false
}

// SetIteration gets a reference to the given int32 and assigns it to the Iteration field.
func (o *MentalModelTraceToolCall) SetIteration(v int32) {
	o.Iteration = &v
}

func (o MentalModelTraceToolCall) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentalModelTraceToolCall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tool"] = o.Tool
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	if !IsNil(o.Input) {
		toSerialize["input"] = o.Input
	}
	if o.Output != nil {
		toSerialize["output"] = o.Output
	}
	if o.UpdatedAt.IsSet() {
		toSerialize["updated_at"] = o.UpdatedAt.Get()
	}
	if o.ResultCount.IsSet() {
		toSerialize["result_count"] = o.ResultCount.Get()
	}
	toSerialize["duration_ms"] = o.DurationMs
	if !IsNil(o.Iteration) {
		toSerialize["iteration"] = o.Iteration
	}
	return toSerialize, nil
}

func (o *MentalModelTraceToolCall) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tool",
		"duration_ms",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMentalModelTraceToolCall := _MentalModelTraceToolCall{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMentalModelTraceToolCall)

	if err != nil {
		return err
	}

	*o = MentalModelTraceToolCall(varMentalModelTraceToolCall)

	return err
}

type NullableMentalModelTraceToolCall struct {
	value *MentalModelTraceToolCall
	isSet bool
}

func (v NullableMentalModelTraceToolCall) Get() *MentalModelTraceToolCall {
	return v.value
}

func (v *NullableMentalModelTraceToolCall) Set(val *MentalModelTraceToolCall) {
	v.value = val
	v.isSet = true
}

func (v NullableMentalModelTraceToolCall) IsSet() bool {
	return v.isSet
}

func (v *NullableMentalModelTraceToolCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentalModelTraceToolCall(val *MentalModelTraceToolCall) *NullableMentalModelTraceToolCall {
	return &NullableMentalModelTraceToolCall{value: val, isSet: true}
}

func (v NullableMentalModelTraceToolCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentalModelTraceToolCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


