/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MentalModelRefreshWindow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentalModelRefreshWindow{}

// MentalModelRefreshWindow The time window a refresh read memories from.
type MentalModelRefreshWindow struct {
	CreatedAfter NullableTime `json:"created_after,omitempty"`
	// Database-time snapshot bounding the refresh. Memories written or edited after this are not read, so they stay newer than the persisted watermark and are caught by the next refresh.
	CreatedBefore time.Time `json:"created_before"`
	Watermark NullableTime `json:"watermark,omitempty"`
}

type _MentalModelRefreshWindow MentalModelRefreshWindow

// NewMentalModelRefreshWindow instantiates a new MentalModelRefreshWindow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentalModelRefreshWindow(createdBefore time.Time) *MentalModelRefreshWindow {
	this := MentalModelRefreshWindow{}
	this.CreatedBefore = createdBefore
	return &this
}

// NewMentalModelRefreshWindowWithDefaults instantiates a new MentalModelRefreshWindow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentalModelRefreshWindowWithDefaults() *MentalModelRefreshWindow {
	this := MentalModelRefreshWindow{}
	return &this
}

// GetCreatedAfter returns the CreatedAfter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshWindow) GetCreatedAfter() time.Time {
	if o == nil || IsNil(o.CreatedAfter.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAfter.Get()
}

// GetCreatedAfterOk returns a tuple with the CreatedAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshWindow) GetCreatedAfterOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedAfter.Get(), o.CreatedAfter.IsSet()
}

// HasCreatedAfter returns a boolean if a field has been set.
func (o *MentalModelRefreshWindow) HasCreatedAfter() bool {
	if o != nil && o.CreatedAfter.IsSet() {
		return true
	}

	return false
}

// SetCreatedAfter gets a reference to the given NullableTime and assigns it to the CreatedAfter field.
func (o *MentalModelRefreshWindow) SetCreatedAfter(v time.Time) {
	o.CreatedAfter.Set(&v)
}
// SetCreatedAfterNil sets the value for CreatedAfter to be an explicit nil
func (o *MentalModelRefreshWindow) SetCreatedAfterNil() {
	o.CreatedAfter.Set(nil)
}

// UnsetCreatedAfter ensures that no value is present for CreatedAfter, not even an explicit nil
func (o *MentalModelRefreshWindow) UnsetCreatedAfter() {
	o.CreatedAfter.Unset()
}

// GetCreatedBefore returns the CreatedBefore field value
func (o *MentalModelRefreshWindow) GetCreatedBefore() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedBefore
}

// GetCreatedBeforeOk returns a tuple with the CreatedBefore field value
// and a boolean to check if the value has been set.
func (o *MentalModelRefreshWindow) GetCreatedBeforeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBefore, true
}

// SetCreatedBefore sets field value
func (o *MentalModelRefreshWindow) SetCreatedBefore(v time.Time) {
	o.CreatedBefore = v
}

// GetWatermark returns the Watermark field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MentalModelRefreshWindow) GetWatermark() time.Time {
	if o == nil || IsNil(o.Watermark.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Watermark.Get()
}

// GetWatermarkOk returns a tuple with the Watermark field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MentalModelRefreshWindow) GetWatermarkOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Watermark.Get(), o.Watermark.IsSet()
}

// HasWatermark returns a boolean if a field has been set.
func (o *MentalModelRefreshWindow) HasWatermark() bool {
	if o != nil && o.Watermark.IsSet() {
		return true
	}

	return false
}

// SetWatermark gets a reference to the given NullableTime and assigns it to the Watermark field.
func (o *MentalModelRefreshWindow) SetWatermark(v time.Time) {
	o.Watermark.Set(&v)
}
// SetWatermarkNil sets the value for Watermark to be an explicit nil
func (o *MentalModelRefreshWindow) SetWatermarkNil() {
	o.Watermark.Set(nil)
}

// UnsetWatermark ensures that no value is present for Watermark, not even an explicit nil
func (o *MentalModelRefreshWindow) UnsetWatermark() {
	o.Watermark.Unset()
}

func (o MentalModelRefreshWindow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentalModelRefreshWindow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAfter.IsSet() {
		toSerialize["created_after"] = o.CreatedAfter.Get()
	}
	toSerialize["created_before"] = o.CreatedBefore
	if o.Watermark.IsSet() {
		toSerialize["watermark"] = o.Watermark.Get()
	}
	return toSerialize, nil
}

func (o *MentalModelRefreshWindow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_before",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMentalModelRefreshWindow := _MentalModelRefreshWindow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMentalModelRefreshWindow)

	if err != nil {
		return err
	}

	*o = MentalModelRefreshWindow(varMentalModelRefreshWindow)

	return err
}

type NullableMentalModelRefreshWindow struct {
	value *MentalModelRefreshWindow
	isSet bool
}

func (v NullableMentalModelRefreshWindow) Get() *MentalModelRefreshWindow {
	return v.value
}

func (v *NullableMentalModelRefreshWindow) Set(val *MentalModelRefreshWindow) {
	v.value = val
	v.isSet = true
}

func (v NullableMentalModelRefreshWindow) IsSet() bool {
	return v.isSet
}

func (v *NullableMentalModelRefreshWindow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentalModelRefreshWindow(val *MentalModelRefreshWindow) *NullableMentalModelRefreshWindow {
	return &NullableMentalModelRefreshWindow{value: val, isSet: true}
}

func (v NullableMentalModelRefreshWindow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentalModelRefreshWindow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


