/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocumentExportSubmitResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentExportSubmitResponse{}

// DocumentExportSubmitResponse Response for the async document-export endpoint (202).  The export runs in the background; poll the operations endpoint for status. On completion the operation's ``result_metadata`` carries ``download_url`` (fetch the ZIP from GET /v1/default/files/download/{key}), ``storage_key``, ``byte_size``, and ``filename``.
type DocumentExportSubmitResponse struct {
	OperationId string `json:"operation_id"`
	Status *string `json:"status,omitempty"`
}

type _DocumentExportSubmitResponse DocumentExportSubmitResponse

// NewDocumentExportSubmitResponse instantiates a new DocumentExportSubmitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentExportSubmitResponse(operationId string) *DocumentExportSubmitResponse {
	this := DocumentExportSubmitResponse{}
	this.OperationId = operationId
	var status string = "pending"
	this.Status = &status
	return &this
}

// NewDocumentExportSubmitResponseWithDefaults instantiates a new DocumentExportSubmitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentExportSubmitResponseWithDefaults() *DocumentExportSubmitResponse {
	this := DocumentExportSubmitResponse{}
	var status string = "pending"
	this.Status = &status
	return &this
}

// GetOperationId returns the OperationId field value
func (o *DocumentExportSubmitResponse) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *DocumentExportSubmitResponse) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *DocumentExportSubmitResponse) SetOperationId(v string) {
	o.OperationId = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DocumentExportSubmitResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentExportSubmitResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DocumentExportSubmitResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DocumentExportSubmitResponse) SetStatus(v string) {
	o.Status = &v
}

func (o DocumentExportSubmitResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentExportSubmitResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operation_id"] = o.OperationId
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

func (o *DocumentExportSubmitResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operation_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentExportSubmitResponse := _DocumentExportSubmitResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentExportSubmitResponse)

	if err != nil {
		return err
	}

	*o = DocumentExportSubmitResponse(varDocumentExportSubmitResponse)

	return err
}

type NullableDocumentExportSubmitResponse struct {
	value *DocumentExportSubmitResponse
	isSet bool
}

func (v NullableDocumentExportSubmitResponse) Get() *DocumentExportSubmitResponse {
	return v.value
}

func (v *NullableDocumentExportSubmitResponse) Set(val *DocumentExportSubmitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentExportSubmitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentExportSubmitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentExportSubmitResponse(val *DocumentExportSubmitResponse) *NullableDocumentExportSubmitResponse {
	return &NullableDocumentExportSubmitResponse{value: val, isSet: true}
}

func (v NullableDocumentExportSubmitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentExportSubmitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


